"""Experimental statistically typed optimization and context-runtime foundation.

The package implements the semantic compiler, measured scheduler, transactional
proposal runtime, structured placement, local exact model-parallel adapter,
geometry-routed torch optimizer execution, and transactional context-action
execution. Real multi-host transport (today's structured executor uses local
worker threads), a general execution adapter for every compiled estimator, and
persistent external retrieval/vector-store adapters remain behind later
dependency gates -- see this package's README.md ("Not implemented yet") for
the full, current boundary.
"""

from mixle.experimental.typed_runtime.acceptance import (
    AcceptanceGateReceipt,
    ClaimKind,
    FrontierClaimAssessment,
    GateStatus,
    ScaleRunReceipt,
    assess_frontier_claims,
)
from mixle.experimental.typed_runtime.benchmark import (
    BenchmarkPoint,
    FailureKind,
    FailureLedger,
    FailureReceipt,
    ObjectiveTarget,
    TargetDirection,
    TimeToTargetTrace,
)
from mixle.experimental.typed_runtime.boundary import (
    BoundaryInbox,
    BoundaryMessage,
    BoundaryMessageKind,
    BoundaryReceipt,
)
from mixle.experimental.typed_runtime.cache import CachedArtifact, InvalidationReceipt, VersionedArtifactCache
from mixle.experimental.typed_runtime.clocks import (
    ClockDecision,
    ClockProgress,
    ClockTrigger,
    MultiRateUpdateClocks,
    UpdateCadence,
)
from mixle.experimental.typed_runtime.compiler import ContractRegistry, compile_update_graph, infer_update_contract
from mixle.experimental.typed_runtime.compression import (
    CompressedDelta,
    CompressionAcknowledgement,
    CompressionMethod,
    CompressionReceipt,
    ErrorFeedbackCompressor,
)
from mixle.experimental.typed_runtime.context_attention import (
    AttentionCandidate,
    ContextAttentionConfig,
    ContextAttentionReceipt,
    ContextAttentionResult,
    bounded_context_attention,
)
from mixle.experimental.typed_runtime.context_execution import (
    ContextActionAdapter,
    ContextActionExecutor,
    ContextActionResult,
    ContextGraphView,
    VerificationUpdate,
)
from mixle.experimental.typed_runtime.context_ir import (
    ContextAction,
    ContextActionKind,
    ContextActionLimits,
    ContextActionReceipt,
    ContextEdge,
    ContextEdgeKind,
    ContextGraph,
    ContextNode,
    ContextNodeKind,
    EvidenceStatus,
    EvidenceTransition,
    FrozenMetadata,
    Provenance,
)
from mixle.experimental.typed_runtime.context_materializer import (
    ContextTokenizer,
    MaterializationPolicy,
    MaterializedContext,
    materialize_context,
)
from mixle.experimental.typed_runtime.context_runtime import (
    ContextActionProvider,
    EffectiveContextRun,
    EffectiveContextRuntime,
)
from mixle.experimental.typed_runtime.context_scheduler import (
    ContextBudget,
    ContextScheduleDecision,
    ContextSchedulerConfig,
    ValueOfInformationScheduler,
)
from mixle.experimental.typed_runtime.contracts import (
    ArtifactKind,
    ComputeBand,
    ConsistencyRequirement,
    ConvergenceCertificate,
    CostEstimate,
    CounterSemantics,
    CurvatureKind,
    MergeLaw,
    ObjectiveKind,
    StateSemantics,
    UpdateContract,
    UpdateKind,
    weakest_band,
    weakest_certificate,
)
from mixle.experimental.typed_runtime.distributed import (
    CollectiveNumericsEvidence,
    plan_distributed_updates,
)
from mixle.experimental.typed_runtime.faults import (
    BoundaryFaultInjector,
    FaultEvent,
    FaultInjectionReceipt,
    FaultKind,
)
from mixle.experimental.typed_runtime.frontier_pilot import (
    GraphMemoryPilotReceipt,
    PilotStrategyReceipt,
    RecoveryDrillReceipt,
    run_graph_memory_pilot,
)
from mixle.experimental.typed_runtime.geometry import (
    BatchSemanticsReceipt,
    CurvatureCache,
    CurvatureSketch,
    GeometryRouterConfig,
    OptimizerEvidence,
    OptimizerFamily,
    OptimizerPlan,
    ParameterDescriptor,
    ParameterRole,
    ParameterRoute,
    apply_optimizer_evidence,
    describe_parameters,
    kronecker_precondition,
    natural_gradient_direction,
    orthogonalized_matrix_direction,
    route_optimizer_geometry,
)
from mixle.experimental.typed_runtime.graph import DependencyEdge, UpdateGraph, UpdateGraphError, UpdateNode
from mixle.experimental.typed_runtime.graph_memory import (
    CachedGraphPartition,
    GraphMemoryCache,
    GraphPartition,
    GraphPartitionPlan,
    GraphPrefetchReceipt,
    partition_context_graph,
)
from mixle.experimental.typed_runtime.hierarchical import (
    CorrectionProvider,
    HierarchicalProposalCoordinator,
    HierarchicalRoundReceipt,
)
from mixle.experimental.typed_runtime.local import (
    GainProvider,
    TypedMixtureRoundReceipt,
    TypedMixtureRun,
    run_typed_mixture_em,
)
from mixle.experimental.typed_runtime.measurement import (
    EffectiveContextMeasurement,
    MeasurementCatalog,
    WorkMeasurement,
)
from mixle.experimental.typed_runtime.planner import ExecutionPlan, plan_execution
from mixle.experimental.typed_runtime.proposal import (
    PayloadMerger,
    ProposalBatch,
    ProposalConflict,
    ProposalPacket,
    merge_same_node_proposals,
    payload_fingerprint,
    proposal_conflicts,
)
from mixle.experimental.typed_runtime.replay import (
    ReplayEntry,
    ReplayLog,
    ReplayMode,
    ReplayReport,
    ReplayStatus,
    ReplayStepReceipt,
    StateProbe,
    replay_log,
)
from mixle.experimental.typed_runtime.scheduler import (
    GainEvidence,
    GainPerCostScheduler,
    NodeScheduleState,
    SchedulerConfig,
    ScheduleReceipt,
)
from mixle.experimental.typed_runtime.staleness import (
    StalenessAction,
    StalenessPolicy,
    StalenessReceipt,
    assess_staleness,
    shrink_proposal,
)
from mixle.experimental.typed_runtime.structured_execution import (
    StructuredEstimationReceipt,
    StructuredEstimationResult,
    run_structured_estimation_step,
)
from mixle.experimental.typed_runtime.topology import (
    ClusterTopology,
    LinkProfile,
    NodePlacement,
    PlacementScope,
    StructuredPlacementPlan,
    StructuredShard,
    TopologyDevice,
    TransferEstimate,
    TransferSample,
    calibrate_links,
    plan_structured_placement,
)
from mixle.experimental.typed_runtime.torch_optimizer import (
    FisherProvider,
    ProjectionProvider,
    build_routed_torch_optimizer,
)
from mixle.experimental.typed_runtime.transaction import (
    ApplyProposalFn,
    CanaryFn,
    CanaryVerdict,
    CommitReceipt,
    CommitStatus,
    FingerprintFn,
    RestoreFn,
    RuntimeVersions,
    SnapshotFn,
    TransactionalCoordinator,
    TransactionParticipant,
)
from mixle.experimental.typed_runtime.validation import (
    IssueSeverity,
    UpdateGraphValidationError,
    ValidationIssue,
    validate_update_graph,
)

__all__ = [
    "AcceptanceGateReceipt",
    "ArtifactKind",
    "ApplyProposalFn",
    "AttentionCandidate",
    "BenchmarkPoint",
    "BoundaryInbox",
    "BoundaryMessage",
    "BoundaryMessageKind",
    "BoundaryReceipt",
    "BatchSemanticsReceipt",
    "BoundaryFaultInjector",
    "CachedArtifact",
    "CachedGraphPartition",
    "CanaryFn",
    "CanaryVerdict",
    "ClaimKind",
    "ClockDecision",
    "ClockProgress",
    "ClockTrigger",
    "ClusterTopology",
    "CollectiveNumericsEvidence",
    "CommitReceipt",
    "CommitStatus",
    "CompressedDelta",
    "CompressionAcknowledgement",
    "CompressionMethod",
    "CompressionReceipt",
    "CorrectionProvider",
    "ConsistencyRequirement",
    "ComputeBand",
    "ConvergenceCertificate",
    "ContextAction",
    "ContextActionKind",
    "ContextActionLimits",
    "ContextActionAdapter",
    "ContextActionExecutor",
    "ContextActionResult",
    "ContextGraphView",
    "ContextAttentionConfig",
    "ContextAttentionReceipt",
    "ContextAttentionResult",
    "ContextActionReceipt",
    "ContextActionProvider",
    "ContextBudget",
    "ContextEdge",
    "ContextEdgeKind",
    "ContextGraph",
    "ContextNode",
    "ContextNodeKind",
    "ContextScheduleDecision",
    "ContextSchedulerConfig",
    "ContextTokenizer",
    "ContractRegistry",
    "CostEstimate",
    "CounterSemantics",
    "CurvatureKind",
    "CurvatureCache",
    "CurvatureSketch",
    "DependencyEdge",
    "EffectiveContextMeasurement",
    "EffectiveContextRun",
    "EffectiveContextRuntime",
    "ErrorFeedbackCompressor",
    "EvidenceTransition",
    "EvidenceStatus",
    "FailureKind",
    "FailureLedger",
    "FailureReceipt",
    "FaultEvent",
    "FaultInjectionReceipt",
    "FaultKind",
    "FisherProvider",
    "FingerprintFn",
    "FrontierClaimAssessment",
    "FrozenMetadata",
    "GainEvidence",
    "GainProvider",
    "GainPerCostScheduler",
    "GeometryRouterConfig",
    "GraphMemoryPilotReceipt",
    "GraphMemoryCache",
    "GraphPartition",
    "GraphPartitionPlan",
    "GraphPrefetchReceipt",
    "GateStatus",
    "IssueSeverity",
    "HierarchicalProposalCoordinator",
    "HierarchicalRoundReceipt",
    "InvalidationReceipt",
    "LinkProfile",
    "MaterializationPolicy",
    "MaterializedContext",
    "MeasurementCatalog",
    "MergeLaw",
    "MultiRateUpdateClocks",
    "NodePlacement",
    "ObjectiveKind",
    "ObjectiveTarget",
    "OptimizerEvidence",
    "OptimizerFamily",
    "OptimizerPlan",
    "ParameterDescriptor",
    "ParameterRole",
    "ParameterRoute",
    "PayloadMerger",
    "PlacementScope",
    "PilotStrategyReceipt",
    "ProposalBatch",
    "ProposalConflict",
    "ProposalPacket",
    "Provenance",
    "ProjectionProvider",
    "RestoreFn",
    "ReplayEntry",
    "ReplayLog",
    "ReplayMode",
    "ReplayReport",
    "ReplayStatus",
    "ReplayStepReceipt",
    "RecoveryDrillReceipt",
    "RuntimeVersions",
    "ScaleRunReceipt",
    "NodeScheduleState",
    "ScheduleReceipt",
    "SchedulerConfig",
    "SnapshotFn",
    "StateSemantics",
    "StateProbe",
    "StalenessAction",
    "StalenessPolicy",
    "StalenessReceipt",
    "StructuredPlacementPlan",
    "StructuredShard",
    "StructuredEstimationReceipt",
    "StructuredEstimationResult",
    "TargetDirection",
    "TimeToTargetTrace",
    "TopologyDevice",
    "TransferEstimate",
    "TransferSample",
    "TypedMixtureRoundReceipt",
    "TypedMixtureRun",
    "TransactionParticipant",
    "TransactionalCoordinator",
    "UpdateContract",
    "UpdateCadence",
    "UpdateGraph",
    "UpdateGraphError",
    "UpdateGraphValidationError",
    "UpdateKind",
    "UpdateNode",
    "ValidationIssue",
    "VersionedArtifactCache",
    "VerificationUpdate",
    "ValueOfInformationScheduler",
    "WorkMeasurement",
    "assess_frontier_claims",
    "assess_staleness",
    "apply_optimizer_evidence",
    "compile_update_graph",
    "ExecutionPlan",
    "plan_execution",
    "plan_distributed_updates",
    "calibrate_links",
    "build_routed_torch_optimizer",
    "bounded_context_attention",
    "infer_update_contract",
    "describe_parameters",
    "kronecker_precondition",
    "merge_same_node_proposals",
    "materialize_context",
    "natural_gradient_direction",
    "orthogonalized_matrix_direction",
    "payload_fingerprint",
    "partition_context_graph",
    "proposal_conflicts",
    "plan_structured_placement",
    "replay_log",
    "validate_update_graph",
    "weakest_band",
    "weakest_certificate",
    "run_typed_mixture_em",
    "run_structured_estimation_step",
    "run_graph_memory_pilot",
    "route_optimizer_geometry",
    "shrink_proposal",
]
