"""Discrete univariate distribution namespace.

Every class implemented under this package is re-exported here so the namespace exposes the API it
actually contains (MXR-080-1231). Before this, the package exposed only its submodule names, so
``from mixle.stats.univariate.discrete import BernoulliAccumulator`` failed while ``from mixle.stats import BernoulliAccumulator``
worked -- the subpackage advertised modules and hid the classes inside them.

``mixle.stats`` remains the consolidated public API and re-exports these same objects; this package
is the narrower namespace for callers who want only discrete univariate families.
"""

from mixle.stats.univariate.discrete.bernoulli import (
    BernoulliAccumulator,
    BernoulliAccumulatorFactory,
    BernoulliDataEncoder,
    BernoulliDistribution,
    BernoulliEnumerator,
    BernoulliEstimator,
    BernoulliSampler,
)
from mixle.stats.univariate.discrete.beta_binomial import (
    BetaBinomialAccumulator,
    BetaBinomialAccumulatorFactory,
    BetaBinomialDataEncoder,
    BetaBinomialDistribution,
    BetaBinomialEnumerator,
    BetaBinomialEstimator,
    BetaBinomialSampler,
)
from mixle.stats.univariate.discrete.binomial import (
    BinomialAccumulator,
    BinomialAccumulatorFactory,
    BinomialDataEncoder,
    BinomialDistribution,
    BinomialEnumerator,
    BinomialEstimator,
    BinomialSampler,
)
from mixle.stats.univariate.discrete.categorical import (
    CategoricalAccumulator,
    CategoricalAccumulatorFactory,
    CategoricalDataEncoder,
    CategoricalDistribution,
    CategoricalEnumerator,
    CategoricalEstimator,
    CategoricalFisherView,
    CategoricalSampler,
)
from mixle.stats.univariate.discrete.geometric import (
    GeometricAccumulator,
    GeometricAccumulatorFactory,
    GeometricDataEncoder,
    GeometricDistribution,
    GeometricEnumerator,
    GeometricEstimator,
    GeometricSampler,
)
from mixle.stats.univariate.discrete.integer_categorical import (
    IntegerCategoricalAccumulator,
    IntegerCategoricalAccumulatorFactory,
    IntegerCategoricalDataEncoder,
    IntegerCategoricalDistribution,
    IntegerCategoricalEnumerator,
    IntegerCategoricalEstimator,
    IntegerCategoricalFisherView,
    IntegerCategoricalSampler,
)
from mixle.stats.univariate.discrete.integer_uniform_spike import (
    IntegerUniformSpikeAccumulator,
    IntegerUniformSpikeAccumulatorFactory,
    IntegerUniformSpikeDataEncoder,
    IntegerUniformSpikeDistribution,
    IntegerUniformSpikeEnumerator,
    IntegerUniformSpikeEstimator,
    IntegerUniformSpikeSampler,
)
from mixle.stats.univariate.discrete.logseries import (
    LogSeriesAccumulator,
    LogSeriesAccumulatorFactory,
    LogSeriesDataEncoder,
    LogSeriesDistribution,
    LogSeriesEnumerator,
    LogSeriesEstimator,
    LogSeriesSampler,
)
from mixle.stats.univariate.discrete.negative_binomial import (
    NegativeBinomialAccumulator,
    NegativeBinomialAccumulatorFactory,
    NegativeBinomialDataEncoder,
    NegativeBinomialDistribution,
    NegativeBinomialEnumerator,
    NegativeBinomialEstimator,
    NegativeBinomialSampler,
)
from mixle.stats.univariate.discrete.point_mass import (
    PointMassAccumulator,
    PointMassAccumulatorFactory,
    PointMassDataEncoder,
    PointMassDistribution,
    PointMassEnumerator,
    PointMassEstimator,
    PointMassSampler,
)
from mixle.stats.univariate.discrete.poisson import (
    PoissonAccumulator,
    PoissonAccumulatorFactory,
    PoissonDataEncoder,
    PoissonDistribution,
    PoissonEnumerator,
    PoissonEstimator,
    PoissonSampler,
)
from mixle.stats.univariate.discrete.skellam import (
    SkellamAccumulator,
    SkellamAccumulatorFactory,
    SkellamDataEncoder,
    SkellamDistribution,
    SkellamEnumerator,
    SkellamEstimator,
    SkellamSampler,
)

__all__ = [
    "BernoulliAccumulator",
    "BernoulliAccumulatorFactory",
    "BernoulliDataEncoder",
    "BernoulliDistribution",
    "BernoulliEnumerator",
    "BernoulliEstimator",
    "BernoulliSampler",
    "BetaBinomialAccumulator",
    "BetaBinomialAccumulatorFactory",
    "BetaBinomialDataEncoder",
    "BetaBinomialDistribution",
    "BetaBinomialEnumerator",
    "BetaBinomialEstimator",
    "BetaBinomialSampler",
    "BinomialAccumulator",
    "BinomialAccumulatorFactory",
    "BinomialDataEncoder",
    "BinomialDistribution",
    "BinomialEnumerator",
    "BinomialEstimator",
    "BinomialSampler",
    "CategoricalAccumulator",
    "CategoricalAccumulatorFactory",
    "CategoricalDataEncoder",
    "CategoricalDistribution",
    "CategoricalEnumerator",
    "CategoricalEstimator",
    "CategoricalFisherView",
    "CategoricalSampler",
    "GeometricAccumulator",
    "GeometricAccumulatorFactory",
    "GeometricDataEncoder",
    "GeometricDistribution",
    "GeometricEnumerator",
    "GeometricEstimator",
    "GeometricSampler",
    "IntegerCategoricalAccumulator",
    "IntegerCategoricalAccumulatorFactory",
    "IntegerCategoricalDataEncoder",
    "IntegerCategoricalDistribution",
    "IntegerCategoricalEnumerator",
    "IntegerCategoricalEstimator",
    "IntegerCategoricalFisherView",
    "IntegerCategoricalSampler",
    "IntegerUniformSpikeAccumulator",
    "IntegerUniformSpikeAccumulatorFactory",
    "IntegerUniformSpikeDataEncoder",
    "IntegerUniformSpikeDistribution",
    "IntegerUniformSpikeEnumerator",
    "IntegerUniformSpikeEstimator",
    "IntegerUniformSpikeSampler",
    "LogSeriesAccumulator",
    "LogSeriesAccumulatorFactory",
    "LogSeriesDataEncoder",
    "LogSeriesDistribution",
    "LogSeriesEnumerator",
    "LogSeriesEstimator",
    "LogSeriesSampler",
    "NegativeBinomialAccumulator",
    "NegativeBinomialAccumulatorFactory",
    "NegativeBinomialDataEncoder",
    "NegativeBinomialDistribution",
    "NegativeBinomialEnumerator",
    "NegativeBinomialEstimator",
    "NegativeBinomialSampler",
    "PointMassAccumulator",
    "PointMassAccumulatorFactory",
    "PointMassDataEncoder",
    "PointMassDistribution",
    "PointMassEnumerator",
    "PointMassEstimator",
    "PointMassSampler",
    "PoissonAccumulator",
    "PoissonAccumulatorFactory",
    "PoissonDataEncoder",
    "PoissonDistribution",
    "PoissonEnumerator",
    "PoissonEstimator",
    "PoissonSampler",
    "SkellamAccumulator",
    "SkellamAccumulatorFactory",
    "SkellamDataEncoder",
    "SkellamDistribution",
    "SkellamEnumerator",
    "SkellamEstimator",
    "SkellamSampler",
]
