"""HMM terminal (absorbing) hidden states: the length is a stopping time, not governed by len_dist."""

import itertools
import unittest

import numpy as np

from pysp.stats import CategoricalDistribution, GaussianDistribution, HiddenMarkovModelDistribution


class HmmTerminalStatesTest(unittest.TestCase):
    def setUp(self):
        self.topics = [CategoricalDistribution({"a": 0.8, "b": 0.2}), CategoricalDistribution({"a": 0.3, "b": 0.7})]
        self.w = [0.7, 0.3]
        self.a = [[0.6, 0.4], [0.5, 0.5]]
        self.d = HiddenMarkovModelDistribution(self.topics, self.w, self.a, terminal_states={1})  # state 1 absorbing

    def _brute(self, x):
        log_w, log_a = np.log(self.w), np.log(self.a)
        total = -np.inf
        for path in itertools.product([0, 1], repeat=len(x)):
            if path[-1] != 1 or any(z == 1 for z in path[:-1]):
                continue  # must end at the terminal state, with no earlier terminal state
            lp = (
                log_w[path[0]]
                + sum(log_a[path[t], path[t + 1]] for t in range(len(x) - 1))
                + sum(self.topics[path[t]].log_density(x[t]) for t in range(len(x)))
            )
            total = np.logaddexp(total, lp)
        return total

    def test_forward_matches_brute_force(self):
        for x in [["b"], ["a", "b"], ["a", "a", "b"], ["b", "a", "a", "b"]]:
            self.assertAlmostEqual(self.d.log_density(x), self._brute(x), places=10)

    def test_normalizes_over_sequences(self):
        total = sum(
            np.exp(self.d.log_density(list(x))) for length in range(1, 13) for x in itertools.product("ab", repeat=length)
        )
        self.assertAlmostEqual(total, 1.0, delta=0.01)  # remaining mass is in sequences longer than 12

    def test_seq_log_density_matches_scalar(self):
        seqs = [["b"], ["a", "b"], ["a", "a", "b"], ["b", "a", "a", "b"]]
        enc = self.d.dist_to_encoder().seq_encode(seqs)
        np.testing.assert_allclose(self.d.seq_log_density(enc), [self.d.log_density(s) for s in seqs], atol=1e-12)

    def test_sampler_paths_end_in_terminal_state(self):
        # Gaussian emissions, distinct so the terminal state is identifiable; state 2 is absorbing
        g = HiddenMarkovModelDistribution(
            [GaussianDistribution(-5, 0.3), GaussianDistribution(0, 0.3), GaussianDistribution(5, 0.3)],
            [0.5, 0.5, 0.0],
            [[0.45, 0.45, 0.1], [0.45, 0.45, 0.1], [0.0, 0.0, 1.0]],
            terminal_states={2},
        )
        s = g.sampler(seed=0).sample(2000)
        self.assertTrue(all(len(seq) >= 1 for seq in s))
        # the last emission is generated by the terminal state (mean ~ 5)
        self.assertGreater(np.mean([seq[-1] for seq in s]), 3.0)
        # and earlier emissions are not (means ~ -5/0)
        self.assertLess(np.mean([e for seq in s if len(seq) > 1 for e in seq[:-1]]), 1.0)

    def test_seq_density_matches_scalar_gaussian(self):
        g = HiddenMarkovModelDistribution(
            [GaussianDistribution(-3, 1), GaussianDistribution(3, 1), GaussianDistribution(0, 0.5)],
            [0.5, 0.4, 0.1],
            [[0.5, 0.3, 0.2], [0.2, 0.6, 0.2], [0.3, 0.3, 0.4]],
            terminal_states={2},
        )
        s = g.sampler(seed=1).sample(25)
        enc = g.dist_to_encoder().seq_encode(s)
        np.testing.assert_allclose(g.seq_log_density(enc), [g.log_density(seq) for seq in s], atol=1e-10)


if __name__ == "__main__":
    unittest.main()
