"""mixle.ppl — an elegant probabilistic-programming surface over mixle.

A model is plain mixle construction with two new things allowed in a parameter
slot: the token ``free`` (estimate it) or another distribution (make it random). Fit
with ``.fit(data)``; query with ``.sample`` / ``.log_prob`` / ``.posterior``.

    from mixle.ppl import Normal, free
    m = Normal(free, free).fit(data)
    m.sample(100)

The ``mixle.stats`` distribution classes are untouched; this is a thin, optional
dialect over the existing model, estimator, and inference contracts.

Layout: the modeling surface and constraints are in :mod:`mixle.ppl.core`; the dialect
constructors (``Normal``/``Gamma``/``Markov``/…) in :mod:`mixle.ppl.distributions`; the
family/composite lowering registry in :mod:`mixle.ppl._lowering` (imported for its
registration side effects); fields/regression/conformal and the PDE-inverse stack in
their own modules. This package init only re-exports.
"""

from __future__ import annotations

from mixle.models.embedding import CategoricalEmbedding as Embedding

# Run the family/composite registrations (import-time side effects) BEFORE the dialect constructors
# and the dynamics operators (which register after the composites) are pulled in.
from mixle.ppl import _lowering  # noqa: F401  (imported for its registration side effects)
from mixle.ppl.conformal import (
    ConformalClassifier,
    ConformalKnowledgeGraph,
    ConformalLinkPredictor,
    ConformalQuantileRegressor,
    ConformalRegressor,
    ConformalStructure,
    conformal,
)
from mixle.ppl.core import (
    Constraint,
    Conv,
    Event,
    Field,
    Group,
    Net,
    RandomVariable,
    Transformer,
    compare,
    concave,
    constrain,
    convex,
    decreasing,
    eq,
    equal,
    free,
    increasing,
    lipschitz,
    lower,
    monotone,
    ne,
    ode_residual,
    ordered,
    potential,
)
from mixle.ppl.density import (
    EBM,
    MAF,
    MDN,
    VAE,
    CondDiscreteAR,
    CondFlow,
    DiscreteAR,
    Flow,
)
from mixle.ppl.diagnostics import loo, loo_stack, loo_stacking_weights, waic
from mixle.ppl.distributions import (
    AR1,
    EMG,
    GEV,
    LDA,
    MVN,
    Bernoulli,
    Beta,
    Binomial,
    Categorical,
    DiagGaussian,
    Dirichlet,
    Exponential,
    Gamma,
    GeneralizedGaussian,
    GeneralizedPareto,
    Geometric,
    Graph,
    Gumbel,
    HalfNormal,
    InverseGamma,
    InverseGaussian,
    Laplace,
    LocalLevel,
    Logistic,
    LogNormal,
    LogSeries,
    Markov,
    Mix,
    Nakagami,
    NegativeBinomial,
    Normal,
    Pareto,
    Poisson,
    Rayleigh,
    Rician,
    SemiMix,
    Seq,
    Skellam,
    SkewNormal,
    StudentT,
    Tweedie,
    Uniform,
    VonMises,
    Weibull,
)
from mixle.ppl.field import (
    GP,
    RBF,
    AnisotropicRBF,
    Cox,
    CustomProxy,
    FieldKernel,
    FieldModel,
    FieldPosterior,
    FieldSystem,
    Gaussian,
    GaussianField,
    GaussianProxy,
    GreatCircleMatern,
    GreatCircleRBF,
    LogisticNicheProxy,
    Niche,
    PoissonProxy,
    Proxy,
    RandomWalk,
    fit_field,
    great_circle_distance,
    joint,
    multistart,
)
from mixle.ppl.guide import AdmixturePosterior, Guide, StructuredVIPosterior, admixture, structured_vi
from mixle.ppl.predictive import (
    posterior_predictive_check,
    prior_predictive,
    prior_predictive_check,
)
from mixle.ppl.priors import Potts, TotalVariation
from mixle.ppl.provenance import fit_with_provenance
from mixle.ppl.summarize import hdi, posterior_summary
from mixle.ppl.survival import censored_loglik, fit_censored, kaplan_meier

__all__ = [
    "RandomVariable",
    "free",
    "ordered",
    "lower",
    "Guide",
    "StructuredVIPosterior",
    "structured_vi",
    "admixture",
    "AdmixturePosterior",
    "Normal",
    "Poisson",
    "Gamma",
    "Exponential",
    "Categorical",
    "Bernoulli",
    "Geometric",
    "Binomial",
    "Weibull",
    "Laplace",
    "Logistic",
    "Uniform",
    "Rayleigh",
    "Pareto",
    "Beta",
    "StudentT",
    "LogNormal",
    "EMG",
    "NegativeBinomial",
    "HalfNormal",
    "InverseGamma",
    "InverseGaussian",
    "Gumbel",
    "SkewNormal",
    "Skellam",
    "LogSeries",
    "VonMises",
    "GEV",
    "Tweedie",
    "GeneralizedGaussian",
    "GeneralizedPareto",
    "Nakagami",
    "Rician",
    "Dirichlet",
    "Conv",
    "Embedding",
    "Mix",
    "Net",
    "Transformer",
    "Flow",
    "MAF",
    "VAE",
    "DiscreteAR",
    "EBM",
    "MDN",
    "CondFlow",
    "CondDiscreteAR",
    "SemiMix",
    "Seq",
    "Markov",
    "LDA",
    "MVN",
    "DiagGaussian",
    "LocalLevel",
    "AR1",
    "Graph",
    "Field",
    "Group",
    "compare",
    "posterior_predictive_check",
    "prior_predictive",
    "prior_predictive_check",
    "fit_censored",
    "fit_with_provenance",
    "censored_loglik",
    "kaplan_meier",
    "hdi",
    "posterior_summary",
    "constrain",
    "Constraint",
    "Event",
    "eq",
    "equal",
    "ne",
    "potential",
    "increasing",
    "decreasing",
    "monotone",
    "convex",
    "concave",
    "lipschitz",
    "ode_residual",
    "GaussianField",
    "FieldSystem",
    "FieldKernel",
    "GreatCircleRBF",
    "GreatCircleMatern",
    "great_circle_distance",
    "RandomWalk",
    "RBF",
    "AnisotropicRBF",
    "Proxy",
    "GaussianProxy",
    "LogisticNicheProxy",
    "PoissonProxy",
    "CustomProxy",
    "fit_field",
    "FieldPosterior",
    "GP",
    "Gaussian",
    "Niche",
    "Cox",
    "joint",
    "FieldModel",
    "TotalVariation",
    "Potts",
    "multistart",
    "conformal",
    "waic",
    "loo",
    "loo_stack",
    "loo_stacking_weights",
    "ConformalRegressor",
    "ConformalClassifier",
    "ConformalQuantileRegressor",
    "ConformalStructure",
    "ConformalLinkPredictor",
    "ConformalKnowledgeGraph",
]
