"""Clayton / Frank / Student-t copula cores (mixle.stats.multivariate): each a drop-in dependence core for
CopulaDistribution. Every core: density integrates to ~1, sample-then-refit recovers its parameter(s), and
its signature dependence shows up (Clayton lower-tail, Frank both signs, Student-t symmetric heavy tails).
Plus: on data generated by one copula, the matching core wins the CopulaDistribution likelihood."""

import unittest

import numpy as np
from scipy.stats import gamma as spgamma
from scipy.stats import norm, spearmanr

import mixle.stats as st
from mixle.inference import optimize
from mixle.stats.combinator.copula import CopulaDistribution
from mixle.stats.multivariate.clayton_copula import ClaytonCopulaDistribution
from mixle.stats.multivariate.frank_copula import FrankCopulaDistribution
from mixle.stats.multivariate.student_t_copula import StudentTCopulaDistribution


def _unit_square_integral(core, m=300):
    g = np.linspace(1e-3, 1 - 1e-3, m)
    u, v = np.meshgrid(g, g)
    dens = np.exp(core.seq_log_density(np.c_[u.ravel(), v.ravel()])).reshape(m, m)
    return float(np.trapezoid(np.trapezoid(dens, g, axis=1), g))


class ClaytonCopulaTest(unittest.TestCase):
    def test_density_integrates_to_one(self):
        self.assertAlmostEqual(_unit_square_integral(ClaytonCopulaDistribution(2, 2.0)), 1.0, delta=0.03)

    def test_sample_then_refit_recovers_theta(self):
        c = ClaytonCopulaDistribution(2, 2.0)
        s = c.sampler(0).sample(4000)
        est = c.estimator().estimate(None, (s, np.ones(len(s))))
        self.assertAlmostEqual(est.theta, 2.0, delta=0.4)

    def test_has_lower_tail_dependence(self):
        s = ClaytonCopulaDistribution(2, 3.0).sampler(0).sample(6000)
        lower = np.mean((s[:, 0] < 0.05) & (s[:, 1] < 0.05))
        upper = np.mean((s[:, 0] > 0.95) & (s[:, 1] > 0.95))
        self.assertGreater(lower, 2.0 * upper)  # dependence concentrated in the lower tail

    def test_supports_higher_dimensions(self):
        c = ClaytonCopulaDistribution(4, 1.5)  # exchangeable d=4, one theta
        s = c.sampler(0).sample(200)
        self.assertEqual(s.shape, (200, 4))
        self.assertTrue(np.isfinite(c.seq_log_density(s)).all())
        est = c.estimator().estimate(None, (s, np.ones(len(s))))  # refit works in d>2
        self.assertGreater(est.theta, 0.5)

    def test_rejects_dim_below_two(self):
        with self.assertRaises(ValueError):
            ClaytonCopulaDistribution(1, 2.0)


class FrankCopulaTest(unittest.TestCase):
    def test_density_integrates_to_one_both_signs(self):
        self.assertAlmostEqual(_unit_square_integral(FrankCopulaDistribution(2, 5.0)), 1.0, delta=0.03)
        self.assertAlmostEqual(_unit_square_integral(FrankCopulaDistribution(2, -5.0)), 1.0, delta=0.03)

    def test_recovers_positive_and_negative_theta(self):
        for th in (5.0, -5.0):
            c = FrankCopulaDistribution(2, th)
            s = c.sampler(0).sample(4000)
            est = c.estimator().estimate(None, (s, np.ones(len(s))))
            self.assertAlmostEqual(est.theta, th, delta=1.0)
            rho, _ = spearmanr(s[:, 0], s[:, 1])
            self.assertEqual(np.sign(rho), np.sign(th))  # sign of dependence follows sign of theta

    def test_theta_zero_is_the_independence_copula(self):
        c = FrankCopulaDistribution(2, 0.0)
        np.testing.assert_allclose(c.seq_log_density(np.array([[0.3, 0.7], [0.1, 0.9]])), 0.0, atol=1e-12)

    def test_is_bivariate_only(self):
        with self.assertRaises(ValueError):
            FrankCopulaDistribution(3, 5.0)


class StudentTCopulaTest(unittest.TestCase):
    def test_density_integrates_to_one(self):
        core = StudentTCopulaDistribution(np.array([[1.0, 0.6], [0.6, 1.0]]), 4.0)
        self.assertAlmostEqual(_unit_square_integral(core), 1.0, delta=0.03)

    def test_refit_recovers_correlation_and_a_low_df(self):
        c = StudentTCopulaDistribution(np.array([[1.0, 0.6], [0.6, 1.0]]), 4.0)
        s = c.sampler(0).sample(5000)
        est = c.estimator().estimate(None, (s, np.ones(len(s))))
        self.assertAlmostEqual(est.corr[0, 1], 0.6, delta=0.08)
        self.assertLess(est.df, 15.0)  # the profile likelihood detects heavy tails, not the Gaussian limit

    def test_has_symmetric_tail_dependence(self):
        s = StudentTCopulaDistribution(np.array([[1.0, 0.5], [0.5, 1.0]]), 3.0).sampler(0).sample(8000)
        lower = np.mean((s[:, 0] < 0.03) & (s[:, 1] < 0.03))
        upper = np.mean((s[:, 0] > 0.97) & (s[:, 1] > 0.97))
        self.assertGreater(lower, 0.002)  # both tails elevated (a Gaussian copula would be far lower)
        self.assertGreater(upper, 0.002)
        self.assertLess(abs(lower - upper), 0.5 * (lower + upper))  # and roughly symmetric

    def test_rejects_non_pd_or_too_small_corr(self):
        with self.assertRaises(ValueError):
            StudentTCopulaDistribution(np.array([[1.0, 1.5], [1.5, 1.0]]), 4.0)  # not PD


class CopulaCoreIntegrationTest(unittest.TestCase):
    def test_each_core_plugs_into_copula_distribution_and_the_matching_core_wins(self):
        # Clayton-dependent data + heterogeneous marginals; fit CopulaDistribution with each core.
        true = ClaytonCopulaDistribution(2, 3.0)
        u = true.sampler(0).sample(1000)
        x0 = spgamma.ppf(u[:, 0], a=2.0, scale=2.0)
        x1 = norm.ppf(u[:, 1], loc=5.0, scale=2.0)
        data = list(zip(x0.tolist(), x1.tolist()))

        def _fit_ll(core):
            proto = CopulaDistribution([st.GammaDistribution(1.0, 1.0), st.GaussianDistribution(0.0, 1.0)], core)
            fit = optimize(data, proto.estimator(), prev_estimate=proto, max_its=4, out=None)
            self.assertAlmostEqual(float(fit.marginals[1].mu), 5.0, delta=0.4)  # marginals still recovered
            return float(np.sum(fit.seq_log_density(fit.dist_to_encoder().seq_encode(data))))

        ll_clayton = _fit_ll(ClaytonCopulaDistribution(2, 0.5))
        ll_frank = _fit_ll(FrankCopulaDistribution(2, 0.0))
        ll_t = _fit_ll(StudentTCopulaDistribution(np.eye(2), 4.0))
        # the correctly-matched (Clayton) core fits Clayton-generated data best
        self.assertGreater(ll_clayton, ll_frank)
        self.assertGreater(ll_clayton, ll_t)


if __name__ == "__main__":
    unittest.main()
