"""HMM terminal (absorbing) hidden states: the length is a stopping time, not governed by len_dist."""

import itertools
import unittest

import numpy as np

from mixle.inference import estimate
from mixle.stats import (
    CategoricalDistribution,
    GaussianDistribution,
    HiddenMarkovModelDistribution,
    HiddenMarkovNonterminationError,
)


class HmmTerminalStatesTest(unittest.TestCase):
    def setUp(self):
        self.topics = [CategoricalDistribution({"a": 0.8, "b": 0.2}), CategoricalDistribution({"a": 0.3, "b": 0.7})]
        self.w = [0.7, 0.3]
        self.a = [[0.6, 0.4], [0.5, 0.5]]
        self.d = HiddenMarkovModelDistribution(self.topics, self.w, self.a, terminal_states={1})  # state 1 absorbing

    def _brute(self, x):
        log_w, log_a = np.log(self.w), np.log(self.a)
        total = -np.inf
        for path in itertools.product([0, 1], repeat=len(x)):
            if path[-1] != 1 or any(z == 1 for z in path[:-1]):
                continue  # must end at the terminal state, with no earlier terminal state
            lp = (
                log_w[path[0]]
                + sum(log_a[path[t], path[t + 1]] for t in range(len(x) - 1))
                + sum(self.topics[path[t]].log_density(x[t]) for t in range(len(x)))
            )
            total = np.logaddexp(total, lp)
        return total

    def test_forward_matches_brute_force(self):
        for x in [["b"], ["a", "b"], ["a", "a", "b"], ["b", "a", "a", "b"]]:
            self.assertAlmostEqual(self.d.log_density(x), self._brute(x), places=10)

    def test_normalizes_over_sequences(self):
        total = sum(
            np.exp(self.d.log_density(list(x)))
            for length in range(1, 11)
            for x in itertools.product("ab", repeat=length)
        )
        self.assertAlmostEqual(total, 1.0, delta=0.01)  # remaining mass is in sequences longer than 10

    def test_seq_log_density_matches_scalar(self):
        seqs = [["b"], ["a", "b"], ["a", "a", "b"], ["b", "a", "a", "b"]]
        enc = self.d.dist_to_encoder().seq_encode(seqs)
        np.testing.assert_allclose(self.d.seq_log_density(enc), [self.d.log_density(s) for s in seqs], atol=1e-12)

    def test_sampler_paths_end_in_terminal_state(self):
        # Gaussian emissions, distinct so the terminal state is identifiable; state 2 is absorbing
        g = HiddenMarkovModelDistribution(
            [GaussianDistribution(-5, 0.3), GaussianDistribution(0, 0.3), GaussianDistribution(5, 0.3)],
            [0.5, 0.5, 0.0],
            [[0.45, 0.45, 0.1], [0.45, 0.45, 0.1], [0.0, 0.0, 1.0]],
            terminal_states={2},
        )
        s = g.sampler(seed=0).sample(2000)
        self.assertTrue(all(len(seq) >= 1 for seq in s))
        # the last emission is generated by the terminal state (mean ~ 5)
        self.assertGreater(np.mean([seq[-1] for seq in s]), 3.0)
        # and earlier emissions are not (means ~ -5/0)
        self.assertLess(np.mean([e for seq in s if len(seq) > 1 for e in seq[:-1]]), 1.0)

    def test_seq_density_matches_scalar_gaussian(self):
        g = HiddenMarkovModelDistribution(
            [GaussianDistribution(-3, 1), GaussianDistribution(3, 1), GaussianDistribution(0, 0.5)],
            [0.5, 0.4, 0.1],
            [[0.5, 0.3, 0.2], [0.2, 0.6, 0.2], [0.3, 0.3, 0.4]],
            terminal_states={2},
        )
        s = g.sampler(seed=1).sample(25)
        enc = g.dist_to_encoder().seq_encode(s)
        np.testing.assert_allclose(g.seq_log_density(enc), [g.log_density(seq) for seq in s], atol=1e-10)

    def test_terminal_state_ids_are_exact_nonempty_and_in_range(self):
        for terminal_states, error in (
            ({1.0}, TypeError),
            ({True}, TypeError),
            (set(), ValueError),
            ({-1}, ValueError),
            ({2}, ValueError),
        ):
            with self.subTest(terminal_states=terminal_states), self.assertRaises(error):
                HiddenMarkovModelDistribution(self.topics, self.w, self.a, terminal_states=terminal_states)

    def test_reachable_nonterminal_trap_is_rejected(self):
        with self.assertRaisesRegex(ValueError, "no path to termination"):
            HiddenMarkovModelDistribution(
                self.topics,
                [1.0, 0.0],
                [[1.0, 0.0], [0.0, 1.0]],
                terminal_states={1},
            )

    def test_capped_terminal_state_sampling_raises_instead_of_returning_off_support(self):
        model = HiddenMarkovModelDistribution(
            self.topics,
            [1.0, 0.0],
            [[0.999, 0.001], [0.0, 1.0]],
            terminal_states={1},
        )
        with self.assertRaises(HiddenMarkovNonterminationError) as raised:
            model.sampler(seed=0).sample_terminal_states(max_steps=1)
        self.assertEqual(raised.exception.mode, "terminal-state")
        self.assertEqual(raised.exception.max_steps, 1)


class QuantizedHmmTerminalStatesTest(unittest.TestCase):
    """The Quantized HMM subclasses the base and inherits terminal-state scoring/sampling/EM."""

    def setUp(self):
        from mixle.stats import QuantizedHiddenMarkovModelDistribution

        self.d = QuantizedHiddenMarkovModelDistribution(
            0.5, ["a", "b"], [[0, 1], [2, 0]], [[0, 1], [2, 0]], initial_exponents=[0, 1], terminal_states={1}
        )

    def _brute(self, x):
        log_w, log_a, topics = self.d.log_w, self.d.log_transitions, self.d.topics
        total = -np.inf
        for path in itertools.product([0, 1], repeat=len(x)):
            if path[-1] != 1 or any(z == 1 for z in path[:-1]):
                continue
            lp = (
                log_w[path[0]]
                + sum(log_a[path[t], path[t + 1]] for t in range(len(x) - 1))
                + sum(topics[path[t]].log_density(x[t]) for t in range(len(x)))
            )
            total = np.logaddexp(total, lp)
        return total

    def test_inherits_terminal_scoring(self):
        self.assertEqual(self.d.terminal_states, {1})
        for x in [["b"], ["a", "b"], ["a", "a", "b"]]:
            self.assertAlmostEqual(self.d.log_density(x), self._brute(x), places=10)
        s = self.d.sampler(seed=0).sample(10)
        enc = self.d.dist_to_encoder().seq_encode(s)
        np.testing.assert_allclose(self.d.seq_log_density(enc), [self.d.log_density(seq) for seq in s], atol=1e-12)


class HmmTerminalStatesEMTest(unittest.TestCase):
    def test_baum_welch_recovers_parameters(self):
        true = HiddenMarkovModelDistribution(
            [GaussianDistribution(-5, 1.0), GaussianDistribution(0, 1.0), GaussianDistribution(5, 1.0)],
            [0.5, 0.5, 0.0],
            [[0.5, 0.4, 0.1], [0.4, 0.5, 0.1], [0.0, 0.0, 1.0]],
            terminal_states={2},  # state 2 absorbing
        )
        data = true.sampler(seed=0).sample(250)
        init = HiddenMarkovModelDistribution(
            [GaussianDistribution(-3, 2.0), GaussianDistribution(1, 2.0), GaussianDistribution(4, 2.0)],
            [0.4, 0.4, 0.2],
            [[0.4, 0.4, 0.2], [0.4, 0.4, 0.2], [0.3, 0.3, 0.4]],
            terminal_states={2},
        )
        m = init
        for _ in range(20):  # terminal-aware Baum-Welch, iterated by the standard estimate() driver
            m = estimate(data, init.estimator(), m)
        self.assertEqual(m.terminal_states, {2})  # stays a terminal-states model
        np.testing.assert_allclose(sorted(t.mu for t in m.topics), [-5.0, 0.0, 5.0], atol=0.2)
        np.testing.assert_allclose(np.sort(m.w), [0.0, 0.46, 0.54], atol=0.05)
        # the non-terminal transition rows recover (the terminal row is never sourced)
        np.testing.assert_allclose(m.transitions[:2, :], [[0.5, 0.4, 0.1], [0.4, 0.5, 0.1]], atol=0.07)
        self.assertGreater(sum(m.log_density(s) for s in data), sum(init.log_density(s) for s in data))


class HmmTerminalValuesSamplerTest(unittest.TestCase):
    """Regression: sample() must dispatch to the terminal-VALUE path when len_dist is Null.

    The len_dist defaults to NullDistribution() (never None), so len_sampler used to be a (non-None)
    null sampler that preempted the terminal_values branch in sample() and crashed.
    """

    def _dist(self):
        return HiddenMarkovModelDistribution(
            [
                CategoricalDistribution({"a": 0.6, "b": 0.3, ".": 0.1}),
                CategoricalDistribution({"a": 0.2, "b": 0.3, ".": 0.5}),
            ],
            [0.7, 0.3],
            [[0.6, 0.4], [0.3, 0.7]],
            terminal_values={"."},
        )

    def test_sample_dispatches_to_terminal_value_path(self):
        s = self._dist().sampler(seed=0).sample(50)  # previously raised TypeError via the len path
        self.assertEqual(len(s), 50)
        for seq in s:
            self.assertEqual(seq[-1], ".")  # ends exactly at the first terminal value
            self.assertNotIn(".", seq[:-1])

    def test_sample_size_none(self):
        self.assertEqual(self._dist().sampler(seed=1).sample()[-1], ".")

    def test_terminal_value_configuration_is_owned_nonempty_and_unambiguous(self):
        values = {"."}
        model = HiddenMarkovModelDistribution(
            [CategoricalDistribution({"a": 0.5, ".": 0.5})],
            [1.0],
            [[1.0]],
            terminal_values=values,
        )
        values.clear()
        self.assertEqual(model.terminal_values, frozenset({"."}))
        with self.assertRaisesRegex(ValueError, "cannot be empty"):
            HiddenMarkovModelDistribution(
                [CategoricalDistribution({"a": 1.0})],
                [1.0],
                [[1.0]],
                terminal_values=set(),
            )
        with self.assertRaisesRegex(ValueError, "cannot combine"):
            HiddenMarkovModelDistribution(
                [CategoricalDistribution({"a": 0.5, ".": 0.5})],
                [1.0],
                [[1.0]],
                terminal_values={"."},
                terminal_states={0},
            )

    def test_capped_terminal_value_sampling_raises_typed_failure(self):
        model = HiddenMarkovModelDistribution(
            [CategoricalDistribution({"a": 1.0})],
            [1.0],
            [[1.0]],
            terminal_values={"."},
        )
        with self.assertRaises(HiddenMarkovNonterminationError) as raised:
            model.sampler(seed=0).sample_terminal(model.terminal_values, max_steps=3)
        self.assertEqual(raised.exception.mode, "terminal-value")
        self.assertEqual(raised.exception.max_steps, 3)


class HmmTerminalValuesDensityTest(unittest.TestCase):
    """terminal_values is a stopping-time density: only sequences whose ONLY terminal value is the last
    are in the support, and the length is endogenous (no len_dist factor). Off-support sequences must
    score -inf so the density is proper (sums to 1 over its support)."""

    def setUp(self):
        self.d = HiddenMarkovModelDistribution(
            [
                CategoricalDistribution({"a": 0.5, "b": 0.3, ".": 0.2}),
                CategoricalDistribution({"a": 0.2, "b": 0.3, ".": 0.5}),
            ],
            [0.6, 0.4],
            [[0.7, 0.3], [0.4, 0.6]],
            terminal_values={"."},
        )

    def test_off_support_is_minus_inf(self):
        for seq in ([], ["a", "b"], ["a", ".", "b", "."], [".", "a", "."]):
            self.assertEqual(self.d.log_density(seq), float("-inf"))

    def test_on_support_matches_enumerator(self):
        for seq, lp in self.d.enumerator().top_k(25):
            self.assertAlmostEqual(self.d.log_density(seq), lp, places=10)

    def test_density_is_proper(self):
        # summing over EVERY finite sequence (incl. would-be off-support) now totals 1 (was > 1 before)
        total = sum(
            np.exp(self.d.log_density(list(s)))
            for length in range(1, 13)
            for s in itertools.product("ab.", repeat=length)
        )
        self.assertAlmostEqual(total, 1.0, delta=0.02)  # remaining mass is in sequences longer than 12

    def test_ambiguous_terminal_defers_structural_count_index(self):
        # shared emissions => a sequence has multiple paths => the structural (path-count) index would be
        # only the tropical projection, so _terminal_values_count_index returns None and seek falls back
        # to exact enumerate-and-bin.
        from mixle.enumeration.quantization.core import Quantizer

        self.assertIsNone(self.d._terminal_values_count_index(Quantizer(bin_width_bits=1.0, oversample=64), 256))
        order = sorted(
            (
                (list(s), self.d.log_density(list(s)))
                for length in range(1, 7)
                for s in itertools.product("ab.", repeat=length)
                if np.isfinite(self.d.log_density(list(s)))
            ),
            key=lambda kv: -kv[1],
        )
        seen = set()
        for k in range(min(len(order), 20)):
            v = tuple(self.d.enumerator().seek(k).value)
            self.assertNotIn(v, seen)  # exact fallback: one sequence per index, no path over-count
            seen.add(v)
            self.assertAlmostEqual(self.d.log_density(list(v)), order[k][1], places=9)


class HmmTerminalValuesDisjointCountIndexTest(unittest.TestCase):
    """Regression: ``_terminal_values_count_index``'s terminal-completion loop silently dropped the
    DEEPEST length class of sequences.

    The loop is ``for length in range(2, built + 1)``, where ``built`` is the deepest length for which
    the all-non-terminal prefix DP ``nt`` was successfully built. Completing a length-``L`` sequence
    (``L - 1`` non-terminal emissions then one terminal emission) needs ``nt[L - 1]``, so the reachable
    lengths are ``2 .. built + 1`` -- but ``range(2, built + 1)`` stops at ``built``, never visiting
    ``length == built + 1`` (the completion off ``nt[built]``, the deepest prefix that was actually
    built). That entire length class vanishes from the index with no signal: ``truncated`` stays False
    because the loss is structural, not budget-driven. These models all use state-disjoint (unambiguous)
    emissions so the structural index applies (doesn't defer to the enumerate-and-bin fallback)."""

    def _cross_check(self, d, true_support, max_fine_bucket=5000):
        """Assert the structural count index is EXACT against an independently-computed true support:
        matching total(), no duplicates, every unranked (value, log_prob) pair correct, and no leftover
        true-support entries the index failed to produce."""
        from mixle.enumeration.quantization.core import Quantizer

        q = Quantizer(bin_width_bits=1.0, oversample=16)
        result = d._terminal_values_count_index(q, max_fine_bucket)
        self.assertIsNotNone(result)  # state-disjoint -> structural index applies, not the fallback
        idx, truncated = result
        self.assertFalse(truncated)
        self.assertEqual(idx.total(), len(true_support))
        h = idx.hist
        seen = set()
        for fb in range(h.base, h.base + len(h.data)):
            for off in range(h.count_at(fb)):
                value, lp = idx.get_in_bucket(fb, off)
                v = tuple(value)
                self.assertNotIn(v, seen)  # no duplicates
                seen.add(v)
                self.assertIn(v, true_support)
                self.assertAlmostEqual(lp, true_support[v], places=9)
        self.assertEqual(seen, set(true_support))  # nothing from the true support was missed

    def test_repro_two_state_drops_deepest_sequence(self):
        # State 1's ONLY emission is terminal, so the deepest all-non-terminal prefix is length 1
        # (state 0 alone): built == 1. Completing it needs length == built + 1 == 2, which the buggy
        # range(2, built + 1) == range(2, 2) is empty and never visits. True support: ['.'] (stopping
        # immediately at state 0) and ['a', '!'] (one non-terminal emission, then state 1's terminal).
        d = HiddenMarkovModelDistribution(
            [CategoricalDistribution({"a": 0.3, ".": 0.7}), CategoricalDistribution({"!": 1.0})],
            [1.0, 0.0],
            [[0.0, 1.0], [0.0, 1.0]],
            terminal_values={".", "!"},
        )
        true_support = {tuple(v): lp for v, lp in d.enumerator().top_k(10)}
        self.assertEqual(len(true_support), 2)
        self._cross_check(d, true_support)

    def test_branching_forward_chain_all_depths_present(self):
        # Three non-terminal states chained strictly forward (0 -> 1 -> 2), each able to jump straight
        # to the terminal state 3 or advance one step: built == 3 (the 0/1/2 chain). Pre-fix, the
        # deepest length class (length == built + 1 == 4) -- all 8 length-4 sequences -- was dropped
        # entirely, along with the correct total (14, not the pre-fix 6).
        topics = [
            CategoricalDistribution({"a": 0.5, "b": 0.5}),
            CategoricalDistribution({"c": 0.5, "d": 0.5}),
            CategoricalDistribution({"e": 0.5, "f": 0.5}),
            CategoricalDistribution({".": 1.0}),
        ]
        w = [1.0, 0.0, 0.0, 0.0]
        a = [
            [0.0, 0.6, 0.0, 0.4],
            [0.0, 0.0, 0.5, 0.5],
            [0.0, 0.0, 0.0, 1.0],
            [0.0, 0.0, 0.0, 0.0],
        ]
        d = HiddenMarkovModelDistribution(topics, w, a, terminal_values={"."})
        true_support = {tuple(v): lp for v, lp in d.enumerator().top_k(20)}
        self.assertEqual(len(true_support), 14)  # 2 (length 2) + 4 (length 3) + 8 (length 4)
        self._cross_check(d, true_support)

    def test_l1_and_deep_tier_coexist_through_terminal_less_state(self):
        # State 0 mixes terminal ('.') and non-terminal (a/b) emissions, so it can stop at length 1
        # (the L == 1 special case); state 1 has NO terminal items at all, so any continuation MUST
        # reach state 2 before it can stop: built == 2. Pre-fix, only length == 2 was attempted (a
        # no-op, since state 1 has no terminal emissions to complete with) and the true length == 3
        # completions (built + 1) were dropped, losing 4 of the 5 true sequences.
        topics = [
            CategoricalDistribution({"a": 0.3, "b": 0.2, ".": 0.5}),
            CategoricalDistribution({"c": 0.5, "d": 0.5}),
            CategoricalDistribution({"!": 1.0}),
        ]
        w = [1.0, 0.0, 0.0]
        a = [
            [0.0, 1.0, 0.0],
            [0.0, 0.0, 1.0],
            [0.0, 0.0, 0.0],
        ]
        d = HiddenMarkovModelDistribution(topics, w, a, terminal_values={".", "!"})
        true_support = {tuple(v): lp for v, lp in d.enumerator().top_k(10)}
        self.assertEqual(len(true_support), 5)  # 1 (length 1) + 4 (length 3); length 2 is unreachable
        self._cross_check(d, true_support)


if __name__ == "__main__":
    unittest.main()
