"""HMM terminal (absorbing) hidden states: the length is a stopping time, not governed by len_dist."""

import itertools
import unittest

import numpy as np

from mixle.inference import estimate
from mixle.stats import CategoricalDistribution, GaussianDistribution, HiddenMarkovModelDistribution


class HmmTerminalStatesTest(unittest.TestCase):
    def setUp(self):
        self.topics = [CategoricalDistribution({"a": 0.8, "b": 0.2}), CategoricalDistribution({"a": 0.3, "b": 0.7})]
        self.w = [0.7, 0.3]
        self.a = [[0.6, 0.4], [0.5, 0.5]]
        self.d = HiddenMarkovModelDistribution(self.topics, self.w, self.a, terminal_states={1})  # state 1 absorbing

    def _brute(self, x):
        log_w, log_a = np.log(self.w), np.log(self.a)
        total = -np.inf
        for path in itertools.product([0, 1], repeat=len(x)):
            if path[-1] != 1 or any(z == 1 for z in path[:-1]):
                continue  # must end at the terminal state, with no earlier terminal state
            lp = (
                log_w[path[0]]
                + sum(log_a[path[t], path[t + 1]] for t in range(len(x) - 1))
                + sum(self.topics[path[t]].log_density(x[t]) for t in range(len(x)))
            )
            total = np.logaddexp(total, lp)
        return total

    def test_forward_matches_brute_force(self):
        for x in [["b"], ["a", "b"], ["a", "a", "b"], ["b", "a", "a", "b"]]:
            self.assertAlmostEqual(self.d.log_density(x), self._brute(x), places=10)

    def test_normalizes_over_sequences(self):
        total = sum(
            np.exp(self.d.log_density(list(x)))
            for length in range(1, 11)
            for x in itertools.product("ab", repeat=length)
        )
        self.assertAlmostEqual(total, 1.0, delta=0.01)  # remaining mass is in sequences longer than 10

    def test_seq_log_density_matches_scalar(self):
        seqs = [["b"], ["a", "b"], ["a", "a", "b"], ["b", "a", "a", "b"]]
        enc = self.d.dist_to_encoder().seq_encode(seqs)
        np.testing.assert_allclose(self.d.seq_log_density(enc), [self.d.log_density(s) for s in seqs], atol=1e-12)

    def test_sampler_paths_end_in_terminal_state(self):
        # Gaussian emissions, distinct so the terminal state is identifiable; state 2 is absorbing
        g = HiddenMarkovModelDistribution(
            [GaussianDistribution(-5, 0.3), GaussianDistribution(0, 0.3), GaussianDistribution(5, 0.3)],
            [0.5, 0.5, 0.0],
            [[0.45, 0.45, 0.1], [0.45, 0.45, 0.1], [0.0, 0.0, 1.0]],
            terminal_states={2},
        )
        s = g.sampler(seed=0).sample(2000)
        self.assertTrue(all(len(seq) >= 1 for seq in s))
        # the last emission is generated by the terminal state (mean ~ 5)
        self.assertGreater(np.mean([seq[-1] for seq in s]), 3.0)
        # and earlier emissions are not (means ~ -5/0)
        self.assertLess(np.mean([e for seq in s if len(seq) > 1 for e in seq[:-1]]), 1.0)

    def test_seq_density_matches_scalar_gaussian(self):
        g = HiddenMarkovModelDistribution(
            [GaussianDistribution(-3, 1), GaussianDistribution(3, 1), GaussianDistribution(0, 0.5)],
            [0.5, 0.4, 0.1],
            [[0.5, 0.3, 0.2], [0.2, 0.6, 0.2], [0.3, 0.3, 0.4]],
            terminal_states={2},
        )
        s = g.sampler(seed=1).sample(25)
        enc = g.dist_to_encoder().seq_encode(s)
        np.testing.assert_allclose(g.seq_log_density(enc), [g.log_density(seq) for seq in s], atol=1e-10)


class QuantizedHmmTerminalStatesTest(unittest.TestCase):
    """The Quantized HMM subclasses the base and inherits terminal-state scoring/sampling/EM."""

    def setUp(self):
        from mixle.stats import QuantizedHiddenMarkovModelDistribution

        self.d = QuantizedHiddenMarkovModelDistribution(
            0.5, ["a", "b"], [[0, 1], [2, 0]], [[0, 1], [2, 0]], initial_exponents=[0, 1], terminal_states={1}
        )

    def _brute(self, x):
        log_w, log_a, topics = self.d.log_w, self.d.log_transitions, self.d.topics
        total = -np.inf
        for path in itertools.product([0, 1], repeat=len(x)):
            if path[-1] != 1 or any(z == 1 for z in path[:-1]):
                continue
            lp = (
                log_w[path[0]]
                + sum(log_a[path[t], path[t + 1]] for t in range(len(x) - 1))
                + sum(topics[path[t]].log_density(x[t]) for t in range(len(x)))
            )
            total = np.logaddexp(total, lp)
        return total

    def test_inherits_terminal_scoring(self):
        self.assertEqual(self.d.terminal_states, {1})
        for x in [["b"], ["a", "b"], ["a", "a", "b"]]:
            self.assertAlmostEqual(self.d.log_density(x), self._brute(x), places=10)
        s = self.d.sampler(seed=0).sample(10)
        enc = self.d.dist_to_encoder().seq_encode(s)
        np.testing.assert_allclose(self.d.seq_log_density(enc), [self.d.log_density(seq) for seq in s], atol=1e-12)


class HmmTerminalStatesEMTest(unittest.TestCase):
    def test_baum_welch_recovers_parameters(self):
        true = HiddenMarkovModelDistribution(
            [GaussianDistribution(-5, 1.0), GaussianDistribution(0, 1.0), GaussianDistribution(5, 1.0)],
            [0.5, 0.5, 0.0],
            [[0.5, 0.4, 0.1], [0.4, 0.5, 0.1], [0.0, 0.0, 1.0]],
            terminal_states={2},  # state 2 absorbing
        )
        data = true.sampler(seed=0).sample(250)
        init = HiddenMarkovModelDistribution(
            [GaussianDistribution(-3, 2.0), GaussianDistribution(1, 2.0), GaussianDistribution(4, 2.0)],
            [0.4, 0.4, 0.2],
            [[0.4, 0.4, 0.2], [0.4, 0.4, 0.2], [0.3, 0.3, 0.4]],
            terminal_states={2},
        )
        m = init
        for _ in range(20):  # terminal-aware Baum-Welch, iterated by the standard estimate() driver
            m = estimate(data, init.estimator(), m)
        self.assertEqual(m.terminal_states, {2})  # stays a terminal-states model
        np.testing.assert_allclose(sorted(t.mu for t in m.topics), [-5.0, 0.0, 5.0], atol=0.2)
        np.testing.assert_allclose(np.sort(m.w), [0.0, 0.46, 0.54], atol=0.05)
        # the non-terminal transition rows recover (the terminal row is never sourced)
        np.testing.assert_allclose(m.transitions[:2, :], [[0.5, 0.4, 0.1], [0.4, 0.5, 0.1]], atol=0.07)
        self.assertGreater(sum(m.log_density(s) for s in data), sum(init.log_density(s) for s in data))


class HmmTerminalValuesSamplerTest(unittest.TestCase):
    """Regression: sample() must dispatch to the terminal-VALUE path when len_dist is Null.

    The len_dist defaults to NullDistribution() (never None), so len_sampler used to be a (non-None)
    null sampler that preempted the terminal_values branch in sample() and crashed.
    """

    def _dist(self):
        return HiddenMarkovModelDistribution(
            [
                CategoricalDistribution({"a": 0.6, "b": 0.3, ".": 0.1}),
                CategoricalDistribution({"a": 0.2, "b": 0.3, ".": 0.5}),
            ],
            [0.7, 0.3],
            [[0.6, 0.4], [0.3, 0.7]],
            terminal_values={"."},
        )

    def test_sample_dispatches_to_terminal_value_path(self):
        s = self._dist().sampler(seed=0).sample(50)  # previously raised TypeError via the len path
        self.assertEqual(len(s), 50)
        for seq in s:
            self.assertEqual(seq[-1], ".")  # ends exactly at the first terminal value
            self.assertNotIn(".", seq[:-1])

    def test_sample_size_none(self):
        self.assertEqual(self._dist().sampler(seed=1).sample()[-1], ".")


class HmmTerminalValuesDensityTest(unittest.TestCase):
    """terminal_values is a stopping-time density: only sequences whose ONLY terminal value is the last
    are in the support, and the length is endogenous (no len_dist factor). Off-support sequences must
    score -inf so the density is proper (sums to 1 over its support)."""

    def setUp(self):
        self.d = HiddenMarkovModelDistribution(
            [
                CategoricalDistribution({"a": 0.5, "b": 0.3, ".": 0.2}),
                CategoricalDistribution({"a": 0.2, "b": 0.3, ".": 0.5}),
            ],
            [0.6, 0.4],
            [[0.7, 0.3], [0.4, 0.6]],
            terminal_values={"."},
        )

    def test_off_support_is_minus_inf(self):
        for seq in ([], ["a", "b"], ["a", ".", "b", "."], [".", "a", "."]):
            self.assertEqual(self.d.log_density(seq), float("-inf"))

    def test_on_support_matches_enumerator(self):
        for seq, lp in self.d.enumerator().top_k(25):
            self.assertAlmostEqual(self.d.log_density(seq), lp, places=10)

    def test_density_is_proper(self):
        # summing over EVERY finite sequence (incl. would-be off-support) now totals 1 (was > 1 before)
        total = sum(
            np.exp(self.d.log_density(list(s)))
            for length in range(1, 13)
            for s in itertools.product("ab.", repeat=length)
        )
        self.assertAlmostEqual(total, 1.0, delta=0.02)  # remaining mass is in sequences longer than 12

    def test_ambiguous_terminal_defers_structural_count_index(self):
        # shared emissions => a sequence has multiple paths => the structural (path-count) index would be
        # only the tropical projection, so _terminal_values_count_index returns None and seek falls back
        # to exact enumerate-and-bin.
        from mixle.enumeration.quantization.core import Quantizer

        self.assertIsNone(self.d._terminal_values_count_index(Quantizer(bin_width_bits=1.0, oversample=64), 256))
        order = sorted(
            (
                (list(s), self.d.log_density(list(s)))
                for length in range(1, 7)
                for s in itertools.product("ab.", repeat=length)
                if np.isfinite(self.d.log_density(list(s)))
            ),
            key=lambda kv: -kv[1],
        )
        seen = set()
        for k in range(min(len(order), 20)):
            v = tuple(self.d.enumerator().seek(k).value)
            self.assertNotIn(v, seen)  # exact fallback: one sequence per index, no path over-count
            seen.add(v)
            self.assertAlmostEqual(self.d.log_density(list(v)), order[k][1], places=9)


if __name__ == "__main__":
    unittest.main()
