"""The maturity manifest is current and covers every public surface (worklist A1.6).

``maturity_manifest.json`` is the committed, machine-readable maturity of every top-level public mixle
surface, generated by ``scripts/gen_maturity_manifest.py`` from the :mod:`mixle.maturity` registry. These
tests pin it: it must be regenerated when the public surface or a tier changes (drift gate), it must cover
every top-level public subpackage, and its anchor tiers must match the registry.
"""

import json
import subprocess
import sys
import unittest
from pathlib import Path

import mixle
from mixle.maturity import maturity_of

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "maturity_manifest.json"
GEN = REPO_ROOT / "scripts" / "gen_maturity_manifest.py"


class MaturityManifestTest(unittest.TestCase):
    def test_manifest_is_not_stale(self):
        # Regenerate and diff: the committed file must equal what the generator produces now.
        proc = subprocess.run([sys.executable, str(GEN), "--check"], cwd=str(REPO_ROOT), capture_output=True, text=True)
        self.assertEqual(
            proc.returncode,
            0,
            f"maturity_manifest.json is stale -- run: python scripts/gen_maturity_manifest.py\n{proc.stderr}",
        )

    def test_manifest_covers_every_public_surface(self):
        import os
        import pkgutil

        surfaces = {
            f"mixle.{m.name}"
            for m in pkgutil.iter_modules([os.path.dirname(mixle.__file__)])
            if not m.name.startswith("_")
        }
        manifest = json.loads(MANIFEST.read_text())
        missing = sorted(surfaces - set(manifest["surfaces"]))
        self.assertEqual(missing, [], f"public surfaces absent from the maturity manifest: {missing}")

    def test_manifest_tiers_match_the_registry(self):
        manifest = json.loads(MANIFEST.read_text())
        for name, entry in manifest["surfaces"].items():
            self.assertEqual(entry["maturity"], maturity_of(name).value, f"{name} tier drifted from the registry")
        # anchors, consistent with A1.2 / A1.5
        self.assertEqual(manifest["surfaces"]["mixle.stats"]["maturity"], "stable")
        self.assertEqual(manifest["surfaces"]["mixle.experimental"]["maturity"], "experimental")


if __name__ == "__main__":
    unittest.main()
