"""Continuous univariate distribution namespace.

Every class implemented under this package is re-exported here so the namespace exposes the API it
actually contains (MXR-080-1231). Before this, the package exposed only its submodule names, so
``from mixle.stats.univariate.continuous import BetaAccumulator`` failed while ``from mixle.stats import BetaAccumulator``
worked -- the subpackage advertised modules and hid the classes inside them.

``mixle.stats`` remains the consolidated public API and re-exports these same objects; this package
is the narrower namespace for callers who want only continuous univariate families.
"""

from mixle.stats.univariate.continuous.beta import (
    BetaAccumulator,
    BetaAccumulatorFactory,
    BetaDataEncoder,
    BetaDistribution,
    BetaEstimator,
    BetaFisherView,
    BetaSampler,
)
from mixle.stats.univariate.continuous.exgaussian import (
    ExponentiallyModifiedGaussianAccumulator,
    ExponentiallyModifiedGaussianAccumulatorFactory,
    ExponentiallyModifiedGaussianDataEncoder,
    ExponentiallyModifiedGaussianDistribution,
    ExponentiallyModifiedGaussianEstimator,
    ExponentiallyModifiedGaussianSampler,
)
from mixle.stats.univariate.continuous.exponential import (
    ExponentialAccumulator,
    ExponentialAccumulatorFactory,
    ExponentialDataEncoder,
    ExponentialDistribution,
    ExponentialEstimator,
    ExponentialSampler,
)
from mixle.stats.univariate.continuous.gamma import (
    GammaAccumulator,
    GammaAccumulatorFactory,
    GammaDataEncoder,
    GammaDistribution,
    GammaEstimator,
    GammaFisherView,
    GammaSampler,
)
from mixle.stats.univariate.continuous.gaussian import (
    GaussianAccumulator,
    GaussianAccumulatorFactory,
    GaussianDataEncoder,
    GaussianDistribution,
    GaussianEstimator,
    GaussianFisherView,
    GaussianSampler,
    GaussianSuffStat,
)
from mixle.stats.univariate.continuous.generalized_extreme_value import (
    GeneralizedExtremeValueAccumulator,
    GeneralizedExtremeValueAccumulatorFactory,
    GeneralizedExtremeValueDataEncoder,
    GeneralizedExtremeValueDistribution,
    GeneralizedExtremeValueEstimator,
    GeneralizedExtremeValueSampler,
)
from mixle.stats.univariate.continuous.generalized_gaussian import (
    GeneralizedGaussianAccumulator,
    GeneralizedGaussianAccumulatorFactory,
    GeneralizedGaussianDataEncoder,
    GeneralizedGaussianDistribution,
    GeneralizedGaussianEstimator,
    GeneralizedGaussianSampler,
)
from mixle.stats.univariate.continuous.generalized_pareto import (
    GeneralizedParetoAccumulator,
    GeneralizedParetoAccumulatorFactory,
    GeneralizedParetoDataEncoder,
    GeneralizedParetoDistribution,
    GeneralizedParetoEstimator,
    GeneralizedParetoSampler,
)
from mixle.stats.univariate.continuous.gumbel import (
    GumbelAccumulator,
    GumbelAccumulatorFactory,
    GumbelDataEncoder,
    GumbelDistribution,
    GumbelEstimator,
    GumbelSampler,
)
from mixle.stats.univariate.continuous.half_normal import (
    HalfNormalAccumulator,
    HalfNormalAccumulatorFactory,
    HalfNormalDataEncoder,
    HalfNormalDistribution,
    HalfNormalEstimator,
    HalfNormalSampler,
)
from mixle.stats.univariate.continuous.inverse_gamma import (
    InverseGammaAccumulator,
    InverseGammaAccumulatorFactory,
    InverseGammaDataEncoder,
    InverseGammaDistribution,
    InverseGammaEstimator,
    InverseGammaSampler,
)
from mixle.stats.univariate.continuous.inverse_gaussian import (
    InverseGaussianAccumulator,
    InverseGaussianAccumulatorFactory,
    InverseGaussianDataEncoder,
    InverseGaussianDistribution,
    InverseGaussianEstimator,
    InverseGaussianSampler,
)
from mixle.stats.univariate.continuous.laplace import (
    LaplaceAccumulator,
    LaplaceAccumulatorFactory,
    LaplaceDataEncoder,
    LaplaceDistribution,
    LaplaceEstimator,
    LaplaceSampler,
)
from mixle.stats.univariate.continuous.log_gaussian import (
    LogGaussianAccumulator,
    LogGaussianAccumulatorFactory,
    LogGaussianDataEncoder,
    LogGaussianDistribution,
    LogGaussianEstimator,
    LogGaussianFisherView,
    LogGaussianSampler,
)
from mixle.stats.univariate.continuous.logistic import (
    LogisticAccumulator,
    LogisticAccumulatorFactory,
    LogisticDataEncoder,
    LogisticDistribution,
    LogisticEstimator,
    LogisticSampler,
)
from mixle.stats.univariate.continuous.nakagami import (
    NakagamiAccumulator,
    NakagamiAccumulatorFactory,
    NakagamiDataEncoder,
    NakagamiDistribution,
    NakagamiEstimator,
    NakagamiSampler,
)
from mixle.stats.univariate.continuous.pareto import (
    ParetoAccumulator,
    ParetoAccumulatorFactory,
    ParetoDataEncoder,
    ParetoDistribution,
    ParetoEstimator,
    ParetoSampler,
)
from mixle.stats.univariate.continuous.rayleigh import (
    RayleighAccumulator,
    RayleighAccumulatorFactory,
    RayleighDataEncoder,
    RayleighDistribution,
    RayleighEstimator,
    RayleighSampler,
)
from mixle.stats.univariate.continuous.rician import (
    RicianAccumulator,
    RicianAccumulatorFactory,
    RicianDataEncoder,
    RicianDistribution,
    RicianEstimator,
    RicianSampler,
)
from mixle.stats.univariate.continuous.skew_normal import (
    SkewNormalAccumulator,
    SkewNormalAccumulatorFactory,
    SkewNormalDataEncoder,
    SkewNormalDistribution,
    SkewNormalEstimator,
    SkewNormalSampler,
)
from mixle.stats.univariate.continuous.student_t import (
    StudentTAccumulator,
    StudentTAccumulatorFactory,
    StudentTDataEncoder,
    StudentTDistribution,
    StudentTEstimator,
    StudentTSampler,
)
from mixle.stats.univariate.continuous.tweedie import (
    TweedieAccumulator,
    TweedieAccumulatorFactory,
    TweedieDataEncoder,
    TweedieDistribution,
    TweedieEstimator,
    TweedieSampler,
    TweedieSeriesResourceError,
)
from mixle.stats.univariate.continuous.uniform import (
    UniformAccumulator,
    UniformAccumulatorFactory,
    UniformDataEncoder,
    UniformDistribution,
    UniformEstimator,
    UniformSampler,
)
from mixle.stats.univariate.continuous.weibull import (
    WeibullAccumulator,
    WeibullAccumulatorFactory,
    WeibullDataEncoder,
    WeibullDistribution,
    WeibullEstimator,
    WeibullSampler,
)

__all__ = [
    "BetaAccumulator",
    "BetaAccumulatorFactory",
    "BetaDataEncoder",
    "BetaDistribution",
    "BetaEstimator",
    "BetaFisherView",
    "BetaSampler",
    "ExponentialAccumulator",
    "ExponentialAccumulatorFactory",
    "ExponentialDataEncoder",
    "ExponentialDistribution",
    "ExponentialEstimator",
    "ExponentialSampler",
    "ExponentiallyModifiedGaussianAccumulator",
    "ExponentiallyModifiedGaussianAccumulatorFactory",
    "ExponentiallyModifiedGaussianDataEncoder",
    "ExponentiallyModifiedGaussianDistribution",
    "ExponentiallyModifiedGaussianEstimator",
    "ExponentiallyModifiedGaussianSampler",
    "GammaAccumulator",
    "GammaAccumulatorFactory",
    "GammaDataEncoder",
    "GammaDistribution",
    "GammaEstimator",
    "GammaFisherView",
    "GammaSampler",
    "GaussianAccumulator",
    "GaussianAccumulatorFactory",
    "GaussianDataEncoder",
    "GaussianDistribution",
    "GaussianEstimator",
    "GaussianFisherView",
    "GaussianSampler",
    "GaussianSuffStat",
    "GeneralizedExtremeValueAccumulator",
    "GeneralizedExtremeValueAccumulatorFactory",
    "GeneralizedExtremeValueDataEncoder",
    "GeneralizedExtremeValueDistribution",
    "GeneralizedExtremeValueEstimator",
    "GeneralizedExtremeValueSampler",
    "GeneralizedGaussianAccumulator",
    "GeneralizedGaussianAccumulatorFactory",
    "GeneralizedGaussianDataEncoder",
    "GeneralizedGaussianDistribution",
    "GeneralizedGaussianEstimator",
    "GeneralizedGaussianSampler",
    "GeneralizedParetoAccumulator",
    "GeneralizedParetoAccumulatorFactory",
    "GeneralizedParetoDataEncoder",
    "GeneralizedParetoDistribution",
    "GeneralizedParetoEstimator",
    "GeneralizedParetoSampler",
    "GumbelAccumulator",
    "GumbelAccumulatorFactory",
    "GumbelDataEncoder",
    "GumbelDistribution",
    "GumbelEstimator",
    "GumbelSampler",
    "HalfNormalAccumulator",
    "HalfNormalAccumulatorFactory",
    "HalfNormalDataEncoder",
    "HalfNormalDistribution",
    "HalfNormalEstimator",
    "HalfNormalSampler",
    "InverseGammaAccumulator",
    "InverseGammaAccumulatorFactory",
    "InverseGammaDataEncoder",
    "InverseGammaDistribution",
    "InverseGammaEstimator",
    "InverseGammaSampler",
    "InverseGaussianAccumulator",
    "InverseGaussianAccumulatorFactory",
    "InverseGaussianDataEncoder",
    "InverseGaussianDistribution",
    "InverseGaussianEstimator",
    "InverseGaussianSampler",
    "LaplaceAccumulator",
    "LaplaceAccumulatorFactory",
    "LaplaceDataEncoder",
    "LaplaceDistribution",
    "LaplaceEstimator",
    "LaplaceSampler",
    "LogGaussianAccumulator",
    "LogGaussianAccumulatorFactory",
    "LogGaussianDataEncoder",
    "LogGaussianDistribution",
    "LogGaussianEstimator",
    "LogGaussianFisherView",
    "LogGaussianSampler",
    "LogisticAccumulator",
    "LogisticAccumulatorFactory",
    "LogisticDataEncoder",
    "LogisticDistribution",
    "LogisticEstimator",
    "LogisticSampler",
    "NakagamiAccumulator",
    "NakagamiAccumulatorFactory",
    "NakagamiDataEncoder",
    "NakagamiDistribution",
    "NakagamiEstimator",
    "NakagamiSampler",
    "ParetoAccumulator",
    "ParetoAccumulatorFactory",
    "ParetoDataEncoder",
    "ParetoDistribution",
    "ParetoEstimator",
    "ParetoSampler",
    "RayleighAccumulator",
    "RayleighAccumulatorFactory",
    "RayleighDataEncoder",
    "RayleighDistribution",
    "RayleighEstimator",
    "RayleighSampler",
    "RicianAccumulator",
    "RicianAccumulatorFactory",
    "RicianDataEncoder",
    "RicianDistribution",
    "RicianEstimator",
    "RicianSampler",
    "SkewNormalAccumulator",
    "SkewNormalAccumulatorFactory",
    "SkewNormalDataEncoder",
    "SkewNormalDistribution",
    "SkewNormalEstimator",
    "SkewNormalSampler",
    "StudentTAccumulator",
    "StudentTAccumulatorFactory",
    "StudentTDataEncoder",
    "StudentTDistribution",
    "StudentTEstimator",
    "StudentTSampler",
    "TweedieAccumulator",
    "TweedieAccumulatorFactory",
    "TweedieDataEncoder",
    "TweedieDistribution",
    "TweedieEstimator",
    "TweedieSampler",
    "TweedieSeriesResourceError",
    "UniformAccumulator",
    "UniformAccumulatorFactory",
    "UniformDataEncoder",
    "UniformDistribution",
    "UniformEstimator",
    "UniformSampler",
    "WeibullAccumulator",
    "WeibullAccumulatorFactory",
    "WeibullDataEncoder",
    "WeibullDistribution",
    "WeibullEstimator",
    "WeibullSampler",
]
