"""HiddenAssociation: learn a translation table when the word alignments are never observed.

Each observation is a PAIR of bags -- a "given" bag of 5 symbols and a "target" bag of 7 -- and every
target symbol was generated by one (unknown) given symbol through a conditional table. The alignment
between the two bags is latent, so EM must sum over all of it while estimating the table; this is the
IBM-Model-1 shape of statistical machine translation, expressed as an ordinary mixle family.

Here the planted table is near-diagonal (``P(a|a) = 0.9``), so a correct fit prints a
``ConditionalDistribution`` whose diagonal is recovered near 0.9 and whose off-diagonals are near 0.05,
alongside the recovered marginal over given symbols.

Takeaway: latent *structure between two fields* is fit by the same ``optimize`` call as a plain
mixture -- you supply the estimator tree that mirrors the model (conditional / given / length) and the
alignment sum happens inside the E-step. Runtime is roughly half a minute to a minute at 1000
observations and 1000 EM iterations.
"""

import numpy as np

from mixle.inference import optimize
from mixle.stats import *

if __name__ == "__main__":
    aa = 0.90
    bb = (1.0 - aa) / 2

    dist1 = CategoricalDistribution({"a": aa, "b": bb, "c": bb})
    dist2 = CategoricalDistribution({"a": bb, "b": aa, "c": bb})
    dist3 = CategoricalDistribution({"a": bb, "b": bb, "c": aa})
    cond_dist = ConditionalDistribution({"a": dist1, "b": dist2, "c": dist3})
    given_dist = MultinomialDistribution(
        CategoricalDistribution({"a": 0.3, "b": 0.2, "c": 0.5}), len_dist=CategoricalDistribution({5: 1.0})
    )
    len_dist = CategoricalDistribution({7: 1.0})
    dist = HiddenAssociationDistribution(cond_dist=cond_dist, given_dist=given_dist, len_dist=len_dist)

    data = dist.sampler(1).sample(1000)

    len_est = CategoricalEstimator()
    given_est = MultinomialEstimator(CategoricalEstimator(), len_estimator=CategoricalEstimator())
    cond_est = ConditionalDistributionEstimator({v: CategoricalEstimator() for v in ["a", "b", "c"]})
    est = HiddenAssociationEstimator(cond_est, given_estimator=given_est, len_estimator=len_est)

    model = optimize(data, est, max_its=1000, rng=np.random.RandomState(1))

    print(str(model))
