"""pysp.ppl — an elegant probabilistic-programming surface over pysparkplug.

A model is plain pysparkplug construction with two new things allowed in a parameter
slot: the token ``free`` (estimate it) or another distribution (make it random). Fit
with ``.fit(data)``; query with ``.sample`` / ``.log_prob`` / ``.posterior``.

    from pysp.ppl import Normal, free
    m = Normal(free, free).fit(data)
    m.sample(100)

The 86 ``pysp.stats`` distribution classes are untouched; this is a thin, optional
dialect. See notes/ppl-syntax-spec.md.

Layout: the modeling surface and constraints are in :mod:`pysp.ppl.core`; the dialect
constructors (``Normal``/``Gamma``/``Markov``/…) in :mod:`pysp.ppl.distributions`; the
family/composite lowering registry in :mod:`pysp.ppl._lowering` (imported for its
registration side effects); fields/regression/conformal and the PDE-inverse stack in
their own modules. This package init only re-exports.
"""

from __future__ import annotations

# Run the family/composite registrations (import-time side effects) BEFORE the dialect constructors
# and the dynamics operators (which register after the composites) are pulled in.
from pysp.ppl import _lowering  # noqa: F401  (imported for its registration side effects)
from pysp.ppl.conformal import (
    ConformalClassifier,
    ConformalKnowledgeGraph,
    ConformalLinkPredictor,
    ConformalQuantileRegressor,
    ConformalRegressor,
    ConformalStructure,
    conformal,
)
from pysp.ppl.core import (
    Constraint,
    Event,
    Field,
    Group,
    RandomVariable,
    compare,
    concave,
    constrain,
    convex,
    decreasing,
    eq,
    equal,
    free,
    increasing,
    lipschitz,
    lower,
    monotone,
    ne,
    ode_residual,
    ordered,
)
from pysp.ppl.distributions import (
    AR1,
    EMG,
    LDA,
    MVN,
    PDE,
    Bernoulli,
    Beta,
    Binomial,
    Categorical,
    DiagGaussian,
    Dirichlet,
    Exponential,
    Gamma,
    Geometric,
    Graph,
    Laplace,
    LocalLevel,
    Logistic,
    LogNormal,
    Markov,
    Mix,
    NegativeBinomial,
    Normal,
    Pareto,
    Poisson,
    Rayleigh,
    SemiMix,
    Seq,
    StudentT,
    Uniform,
    Weibull,
)
from pysp.ppl.field import (
    GP,
    RBF,
    AnisotropicRBF,
    Cox,
    CustomProxy,
    FieldKernel,
    FieldModel,
    FieldPosterior,
    FieldSystem,
    Gaussian,
    GaussianField,
    GaussianProxy,
    GreatCircleMatern,
    GreatCircleRBF,
    LogisticNicheProxy,
    Niche,
    PoissonProxy,
    Proxy,
    RandomWalk,
    fit_field,
    great_circle_distance,
    joint,
    multistart,
)
from pysp.ppl.physics.dynamics import (
    AdvectionDiffusionOperator,
    AdvectionOperator,
    DiffusionOperator,
    available_dynamics_operators,
    make_operator,
    register_dynamics_operator,
)
from pysp.ppl.physics.flow import NavierStokes2D
from pysp.ppl.physics.inverse import Differential
from pysp.ppl.physics.multiphysics import CoupledPDESystem, solve_poisson
from pysp.ppl.physics.shape import level_set_material, shape_optimize
from pysp.ppl.physics.wave import WaveEquation2D
from pysp.ppl.priors import Potts, TotalVariation

__all__ = [
    "RandomVariable",
    "free",
    "ordered",
    "lower",
    "Normal",
    "Poisson",
    "Gamma",
    "Exponential",
    "Categorical",
    "Bernoulli",
    "Geometric",
    "Binomial",
    "Weibull",
    "Laplace",
    "Logistic",
    "Uniform",
    "Rayleigh",
    "Pareto",
    "Beta",
    "StudentT",
    "LogNormal",
    "EMG",
    "NegativeBinomial",
    "Dirichlet",
    "Mix",
    "SemiMix",
    "Seq",
    "Markov",
    "LDA",
    "MVN",
    "DiagGaussian",
    "LocalLevel",
    "AR1",
    "PDE",
    "DiffusionOperator",
    "AdvectionOperator",
    "AdvectionDiffusionOperator",
    "make_operator",
    "register_dynamics_operator",
    "available_dynamics_operators",
    "Graph",
    "Field",
    "Group",
    "compare",
    "constrain",
    "Constraint",
    "Event",
    "eq",
    "equal",
    "ne",
    "increasing",
    "decreasing",
    "monotone",
    "convex",
    "concave",
    "lipschitz",
    "ode_residual",
    "GaussianField",
    "FieldSystem",
    "FieldKernel",
    "GreatCircleRBF",
    "GreatCircleMatern",
    "great_circle_distance",
    "RandomWalk",
    "RBF",
    "AnisotropicRBF",
    "Proxy",
    "GaussianProxy",
    "LogisticNicheProxy",
    "PoissonProxy",
    "CustomProxy",
    "fit_field",
    "FieldPosterior",
    "GP",
    "Gaussian",
    "Niche",
    "Cox",
    "joint",
    "FieldModel",
    "Differential",
    "shape_optimize",
    "level_set_material",
    "TotalVariation",
    "Potts",
    "multistart",
    "NavierStokes2D",
    "solve_poisson",
    "CoupledPDESystem",
    "WaveEquation2D",
    "conformal",
    "ConformalRegressor",
    "ConformalClassifier",
    "ConformalQuantileRegressor",
    "ConformalStructure",
    "ConformalLinkPredictor",
    "ConformalKnowledgeGraph",
]
