"""Public multivariate probability-model namespace.

The same names are available as attributes of :mod:`mixle.stats`. Distribution and
estimator classes form the curated star-import surface there; this focused namespace
also exposes the sampler, encoder, accumulator, receipt, and exact-enumerator types
needed by framework integrations.
"""

from mixle.stats.multivariate.categorical_multinomial import (
    MultinomialAccumulator,
    MultinomialAccumulatorFactory,
    MultinomialDataEncoder,
    MultinomialDistribution,
    MultinomialEncodedData,
    MultinomialEnumerator,
    MultinomialEstimator,
    MultinomialFisherView,
    MultinomialSampler,
)
from mixle.stats.multivariate.clayton_copula import (
    ClaytonCopulaDistribution,
    ClaytonCopulaEstimator,
    ClaytonCopulaSampler,
)
from mixle.stats.multivariate.composition import (
    AitchisonNormalAccumulator,
    AitchisonNormalDataEncoder,
    AitchisonNormalDistribution,
    AitchisonNormalEstimator,
    AitchisonNormalSampler,
    closure,
    clr,
    clr_inv,
    ilr,
    ilr_basis,
    ilr_inv,
)
from mixle.stats.multivariate.diagonal_gaussian import (
    DiagonalGaussianAccumulator,
    DiagonalGaussianAccumulatorFactory,
    DiagonalGaussianDataEncoder,
    DiagonalGaussianDistribution,
    DiagonalGaussianEstimator,
    DiagonalGaussianFisherView,
    DiagonalGaussianSampler,
)
from mixle.stats.multivariate.dirichlet_multinomial import (
    DirichletMultinomialAccumulator,
    DirichletMultinomialAccumulatorFactory,
    DirichletMultinomialDataEncoder,
    DirichletMultinomialDistribution,
    DirichletMultinomialEnumerator,
    DirichletMultinomialEstimator,
    DirichletMultinomialFitReceipt,
    DirichletMultinomialResourceError,
    DirichletMultinomialSampler,
)
from mixle.stats.multivariate.frank_copula import (
    FrankCopulaDistribution,
    FrankCopulaEstimator,
    FrankCopulaSampler,
)
from mixle.stats.multivariate.gaussian_copula import (
    GaussianCopulaAccumulator,
    GaussianCopulaAccumulatorFactory,
    GaussianCopulaDataEncoder,
    GaussianCopulaDistribution,
    GaussianCopulaEstimator,
    GaussianCopulaSampler,
)
from mixle.stats.multivariate.gumbel_copula import (
    GumbelCopulaDistribution,
    GumbelCopulaEstimator,
    GumbelCopulaSampler,
)
from mixle.stats.multivariate.integer_multinomial import (
    IntegerMultinomialAccumulator,
    IntegerMultinomialAccumulatorFactory,
    IntegerMultinomialDataEncoder,
    IntegerMultinomialDistribution,
    IntegerMultinomialEnumerator,
    IntegerMultinomialEstimator,
    IntegerMultinomialSampler,
)
from mixle.stats.multivariate.multivariate_gaussian import (
    MultivariateGaussianAccumulator,
    MultivariateGaussianAccumulatorFactory,
    MultivariateGaussianDataEncoder,
    MultivariateGaussianDistribution,
    MultivariateGaussianEstimator,
    MultivariateGaussianFisherView,
    MultivariateGaussianSampler,
)
from mixle.stats.multivariate.multivariate_student_t import (
    MultivariateStudentTAccumulator,
    MultivariateStudentTAccumulatorFactory,
    MultivariateStudentTDataEncoder,
    MultivariateStudentTDistribution,
    MultivariateStudentTEstimator,
    MultivariateStudentTSampler,
)
from mixle.stats.multivariate.rvine_copula import (
    RVineCopulaDistribution,
    RVineCopulaEstimator,
    RVineCopulaSampler,
)
from mixle.stats.multivariate.student_t_copula import (
    StudentTCopulaDistribution,
    StudentTCopulaEstimator,
    StudentTCopulaSampler,
)
from mixle.stats.multivariate.vine_copula import (
    ClaytonPairCopula,
    CVineCopulaDistribution,
    CVineCopulaEstimator,
    CVineCopulaSampler,
    DVineCopulaDistribution,
    DVineCopulaEstimator,
    DVineCopulaSampler,
    FrankPairCopula,
    GaussianPairCopula,
    GumbelPairCopula,
    IndependencePairCopula,
    PairCandidateEvidence,
    PairSelectionReceipt,
    StudentTPairCopula,
    VinePairFitError,
)

__all__ = [
    "closure",
    "clr",
    "clr_inv",
    "ilr",
    "ilr_inv",
    "ilr_basis",
    "AitchisonNormalDistribution",
    "AitchisonNormalSampler",
    "AitchisonNormalDataEncoder",
    "AitchisonNormalEstimator",
    "AitchisonNormalAccumulator",
    "MultinomialDistribution",
    "MultinomialSampler",
    "MultinomialEstimator",
    "MultinomialDataEncoder",
    "MultinomialEncodedData",
    "MultinomialEnumerator",
    "MultinomialAccumulator",
    "MultinomialAccumulatorFactory",
    "MultinomialFisherView",
    "IntegerMultinomialDistribution",
    "IntegerMultinomialSampler",
    "IntegerMultinomialEstimator",
    "IntegerMultinomialDataEncoder",
    "IntegerMultinomialEnumerator",
    "IntegerMultinomialAccumulator",
    "IntegerMultinomialAccumulatorFactory",
    "DirichletMultinomialDistribution",
    "DirichletMultinomialSampler",
    "DirichletMultinomialEstimator",
    "DirichletMultinomialDataEncoder",
    "DirichletMultinomialEnumerator",
    "DirichletMultinomialAccumulator",
    "DirichletMultinomialAccumulatorFactory",
    "DirichletMultinomialFitReceipt",
    "DirichletMultinomialResourceError",
    "DiagonalGaussianDistribution",
    "DiagonalGaussianSampler",
    "DiagonalGaussianEstimator",
    "DiagonalGaussianDataEncoder",
    "DiagonalGaussianAccumulator",
    "DiagonalGaussianAccumulatorFactory",
    "DiagonalGaussianFisherView",
    "MultivariateGaussianDistribution",
    "MultivariateGaussianSampler",
    "MultivariateGaussianEstimator",
    "MultivariateGaussianDataEncoder",
    "MultivariateGaussianAccumulator",
    "MultivariateGaussianAccumulatorFactory",
    "MultivariateGaussianFisherView",
    "MultivariateStudentTDistribution",
    "MultivariateStudentTSampler",
    "MultivariateStudentTEstimator",
    "MultivariateStudentTDataEncoder",
    "MultivariateStudentTAccumulator",
    "MultivariateStudentTAccumulatorFactory",
    "GaussianCopulaDistribution",
    "GaussianCopulaSampler",
    "GaussianCopulaEstimator",
    "GaussianCopulaDataEncoder",
    "GaussianCopulaAccumulator",
    "GaussianCopulaAccumulatorFactory",
    "ClaytonCopulaDistribution",
    "ClaytonCopulaSampler",
    "ClaytonCopulaEstimator",
    "FrankCopulaDistribution",
    "FrankCopulaSampler",
    "FrankCopulaEstimator",
    "GumbelCopulaDistribution",
    "GumbelCopulaSampler",
    "GumbelCopulaEstimator",
    "StudentTCopulaDistribution",
    "StudentTCopulaSampler",
    "StudentTCopulaEstimator",
    "IndependencePairCopula",
    "GaussianPairCopula",
    "ClaytonPairCopula",
    "FrankPairCopula",
    "GumbelPairCopula",
    "StudentTPairCopula",
    "VinePairFitError",
    "PairCandidateEvidence",
    "PairSelectionReceipt",
    "CVineCopulaDistribution",
    "CVineCopulaSampler",
    "CVineCopulaEstimator",
    "DVineCopulaDistribution",
    "DVineCopulaSampler",
    "DVineCopulaEstimator",
    "RVineCopulaDistribution",
    "RVineCopulaSampler",
    "RVineCopulaEstimator",
]
