"""``HamiltonianNet`` -- a learned dynamical system that conserves its own energy, by construction.

An ordinary neural net fit to a system's ``(q, p) -> (dq/dt, dp/dt)`` derivatives has no reason to conserve
anything: it is free to predict a vector field whose flow spirals in or out, even if the true physical system
is energy-conserving. A Hamiltonian network (Greydanus, Dzamba & Yosinski, 2019) instead learns a single
SCALAR function ``H(q, p)`` (an MLP) and reads the dynamics off its symplectic gradient::

    dq/dt =  dH/dp
    dp/dt = -dH/dq

Along any trajectory generated by exactly this vector field, ``dH/dt = dH/dq . dq/dt + dH/dp . dp/dt
= dH/dq . dH/dp - dH/dp . dH/dq = 0`` identically -- ``H`` is conserved along the flow for ANY choice of the
network's weights, trained or not. This is the same "hard constraint, not a soft penalty" idea as
:class:`~mixle.models.pinn.PINNRegression` (which only penalizes a residual) and :func:`~mixle.models.neural.make_monotonic_mlp`/
:func:`~mixle.models.energy.build_convex_energy_net` (which enforce a shape by reparameterizing weights):
here the architecture itself makes conservation a property of the *dynamics*, not of the density.

``leapfrog_rollout`` integrates the learned (or true) vector field with a symplectic (leapfrog) scheme, which
keeps the *discretized* trajectory's energy error bounded and oscillating rather than drifting away over long
rollouts -- the numerical-integration counterpart of the continuous-time conservation property above.

Requires torch.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from mixle.models.neural import make_mlp


class HamiltonianNet:
    """Learns a scalar ``H(q, p)`` and exposes the symplectic-gradient dynamics it implies.

    ``dim`` is the dimension of ``q`` (and of ``p``, always equal); ``hidden`` sizes the MLP computing
    ``H`` from the concatenated ``(q, p)``. ``module`` (the underlying ``torch.nn.Module``) is exposed
    directly for training with an ordinary optimizer loop against derivative-matching data.
    """

    def __init__(self, dim: int, hidden: Sequence[int] = (64, 64)) -> None:
        if int(dim) <= 0:
            raise ValueError("HamiltonianNet dim must be positive; got %r" % (dim,))
        self.dim = int(dim)
        self.module = make_mlp(2 * self.dim, hidden, 1, activation="tanh")  # tanh: smooth second derivatives

    def hamiltonian(self, q: Any, p: Any) -> Any:
        """``H(q, p)``, shape ``(...,)`` -- squeezes the module's scalar output dimension."""
        torch = _torch()
        qp = torch.cat([q, p], dim=-1)
        return self.module(qp).squeeze(-1)

    def time_derivative(self, q: Any, p: Any) -> tuple[Any, Any]:
        """``(dq/dt, dp/dt) = (dH/dp, -dH/dq)`` via autograd -- the symplectic gradient of ``hamiltonian``.

        ``q``/``p`` must be leaf tensors (``requires_grad_(True)``) or already part of an active graph;
        the returned derivatives carry gradients back through ``self.module``'s parameters, so this composes
        into a training loop that fits derivative-matching data end to end.
        """
        torch = _torch()
        h = self.hamiltonian(q, p).sum()
        dh_dq, dh_dp = torch.autograd.grad(h, [q, p], create_graph=True)
        return dh_dp, -dh_dq


def leapfrog_rollout(net: HamiltonianNet, q0: Any, p0: Any, dt: float, n_steps: int) -> tuple[Any, Any]:
    """Symplectic leapfrog integration of ``net``'s learned (or untrained) Hamiltonian flow.

    Returns ``(qs, ps)``, each shaped ``(n_steps + 1, *q0.shape)`` -- the trajectory including the initial
    state. A symplectic integrator is the right numerical counterpart to a conservative continuous-time
    system: unlike a generic (e.g. Euler) integrator, its energy error stays bounded and oscillates rather
    than drifting monotonically over long rollouts.
    """
    torch = _torch()
    q, p = q0.clone(), p0.clone()
    qs, ps = [q.clone()], [p.clone()]
    for _ in range(int(n_steps)):
        q_req, p_req = q.detach().requires_grad_(True), p.detach().requires_grad_(True)
        _, dp_half = net.time_derivative(q_req, p_req)
        p_half = p + 0.5 * dt * dp_half.detach()

        q_req2, p_req2 = q.detach().requires_grad_(True), p_half.detach().requires_grad_(True)
        dq_full, _ = net.time_derivative(q_req2, p_req2)
        q = q + dt * dq_full.detach()

        q_req3, p_req3 = q.detach().requires_grad_(True), p_half.detach().requires_grad_(True)
        _, dp_half2 = net.time_derivative(q_req3, p_req3)
        p = p_half + 0.5 * dt * dp_half2.detach()

        qs.append(q.clone())
        ps.append(p.clone())
    return torch.stack(qs), torch.stack(ps)


def _torch() -> Any:
    try:
        import torch
    except ImportError as e:  # pragma: no cover
        raise ImportError("mixle.models.hamiltonian requires torch.") from e
    return torch
